# vocab_data.py
# 真实难度递进词库：每个词独立造句，拒绝模板句

GLOBAL_VOCAB_DB = {
    # -------------------------------------------------------------
    # Level 1: 职场学习、城市交通、食物味道与时间频率 - 100词 (原 Level 3)
    # -------------------------------------------------------------
    1: [
        {"word": "office", "phonetic": "/ˈɒfɪs/", "meaning": "n. 办公室", "example_en": "I left my umbrella in the office.", "example_cn": "我把伞落在办公室了。"},
        {"word": "boss", "phonetic": "/bɒs/", "meaning": "n. 老板", "example_en": "My boss gave me a new project today.", "example_cn": "我老板今天交给我一个新项目。"},
        {"word": "job", "phonetic": "/dʒɒb/", "meaning": "n. 工作", "example_en": "Finding a good job is not easy.", "example_cn": "找一份好工作并不容易。"},
        {"word": "meeting", "phonetic": "/ˈmiːtɪŋ/", "meaning": "n. 会议", "example_en": "We have a team meeting at 10 AM.", "example_cn": "我们上午10点有个团队会议。"},
        {"word": "break", "phonetic": "/breɪk/", "meaning": "n. 休息", "example_en": "Let's take a ten-minute break.", "example_cn": "我们休息十分钟吧。"},
        {"word": "student", "phonetic": "/ˈstjuːdnt/", "meaning": "n. 学生", "example_en": "The student asked the teacher a question.", "example_cn": "那个学生问了老师一个问题。"},
        {"word": "class", "phonetic": "/klɑːs/", "meaning": "n. 课程；班级", "example_en": "I was late for my English class.", "example_cn": "我的英语课迟到了。"},
        {"word": "homework", "phonetic": "/ˈhəʊmwɜːk/", "meaning": "n. 家庭作业", "example_en": "Did you finish your math homework?", "example_cn": "你做完数学作业了吗？"},
        {"word": "test", "phonetic": "/test/", "meaning": "n. 测试，考试", "example_en": "I need to study for the driving test.", "example_cn": "我需要为驾照考试做准备。"},
        {"word": "pass", "phonetic": "/pɑːs/", "meaning": "v. 通过", "example_en": "She studied hard and passed the exam.", "example_cn": "她努力学习并通过了考试。"},
        {"word": "fail", "phonetic": "/feɪl/", "meaning": "v. 失败，不及格", "example_en": "Don't worry if you fail, just try again.", "example_cn": "如果不及格别担心，再试一次就好。"},
        {"word": "easy", "phonetic": "/ˈiːzi/", "meaning": "adj. 容易的", "example_en": "This puzzle is too easy for me.", "example_cn": "这个谜题对我来说太简单了。"},
        {"word": "hard", "phonetic": "/hɑːd/", "meaning": "adj. 困难的；努力的", "example_en": "He works hard to support his family.", "example_cn": "他努力工作来养家。"},
        {"word": "learn", "phonetic": "/lɜːn/", "meaning": "v. 学习", "example_en": "I want to learn how to play the guitar.", "example_cn": "我想学习弹吉他。"},
        {"word": "study", "phonetic": "/ˈstʌdi/", "meaning": "v. 学习，研究", "example_en": "We study in the library every afternoon.", "example_cn": "我们每天下午在图书馆学习。"},
        {"word": "use", "phonetic": "/juːz/", "meaning": "v. 使用", "example_en": "Can I use your phone for a second?", "example_cn": "我能用一下你的手机吗？"},
        {"word": "try", "phonetic": "/traɪ/", "meaning": "v. 尝试", "example_en": "You should try this delicious cake.", "example_cn": "你应该尝尝这块美味的蛋糕。"},
        {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "v. 改变，更换", "example_en": "I need to change my clothes before the party.", "example_cn": "派对前我需要换身衣服。"},
        {"word": "wait", "phonetic": "/weɪt/", "meaning": "v. 等待", "example_en": "Please wait for me at the entrance.", "example_cn": "请在入口处等我。"},
        {"word": "help", "phonetic": "/help/", "meaning": "v./n. 帮助", "example_en": "Thank you so much for your help.", "example_cn": "非常感谢你的帮助。"},
        {"word": "street", "phonetic": "/striːt/", "meaning": "n. 街道", "example_en": "Look both ways before crossing the street.", "example_cn": "过马路前要注意两边。"},
        {"word": "avenue", "phonetic": "/ˈævənjuː/", "meaning": "n. 大道", "example_en": "Their shop is located on Fifth Avenue.", "example_cn": "他们的店位于第五大道。"},
        {"word": "traffic", "phonetic": "/ˈtræfɪk/", "meaning": "n. 交通", "example_en": "The traffic is always terrible in the morning.", "example_cn": "早上的交通总是很糟糕。"},
        {"word": "bridge", "phonetic": "/brɪdʒ/", "meaning": "n. 桥梁", "example_en": "We drove across the golden bridge.", "example_cn": "我们开车驶过了那座金色的桥。"},
        {"word": "corner", "phonetic": "/ˈkɔːnə(r)/", "meaning": "n. 角落，拐角", "example_en": "The coffee shop is right around the corner.", "example_cn": "那家咖啡店就在拐角处。"},
        {"word": "map", "phonetic": "/mæp/", "meaning": "n. 地图", "example_en": "Let me check the map on my phone.", "example_cn": "让我查一下手机上的地图。"},
        {"word": "block", "phonetic": "/blɒk/", "meaning": "n. 街区", "example_en": "Walk two blocks and turn left.", "example_cn": "走两个街区然后左转。"},
        {"word": "subway", "phonetic": "/ˈsʌbweɪ/", "meaning": "n. 地铁", "example_en": "Taking the subway is faster than taking a taxi.", "example_cn": "坐地铁比打车快。"},
        {"word": "bicycle", "phonetic": "/ˈbaɪsɪkl/", "meaning": "n. 自行车", "example_en": "She rides her bicycle to work every day.", "example_cn": "她每天骑自行车上班。"},
        {"word": "drive", "phonetic": "/draɪv/", "meaning": "v. 驾驶", "example_en": "It takes an hour to drive to the airport.", "example_cn": "开车去机场需要一个小时。"},
        {"word": "ride", "phonetic": "/raɪd/", "meaning": "v. 骑", "example_en": "He likes to ride a horse on the farm.", "example_cn": "他喜欢在农场里骑马。"},
        {"word": "stop", "phonetic": "/stɒp/", "meaning": "v. 停止", "example_en": "The bus will stop at the next station.", "example_cn": "公交车将在下一站停车。"},
        {"word": "fast", "phonetic": "/fɑːst/", "meaning": "adj./adv. 快的", "example_en": "Don't drive so fast, it's dangerous.", "example_cn": "别开这么快，很危险。"},
        {"word": "slow", "phonetic": "/sləʊ/", "meaning": "adj. 慢的", "example_en": "The internet connection is very slow today.", "example_cn": "今天的网络连接非常慢。"},
        {"word": "trip", "phonetic": "/trɪp/", "meaning": "n. 旅行", "example_en": "How was your business trip to London?", "example_cn": "你去伦敦的出差顺利吗？"},
        {"word": "vacation", "phonetic": "/vəˈkeɪʃn/", "meaning": "n. 假期", "example_en": "I need a long vacation to relax.", "example_cn": "我需要一个长假来放松一下。"},
        {"word": "guide", "phonetic": "/ɡaɪd/", "meaning": "n. 导游；指南", "example_en": "Our tour guide was very friendly and helpful.", "example_cn": "我们的导游非常友好并且乐于助人。"},
        {"word": "tour", "phonetic": "/tʊə(r)/", "meaning": "n. 参观，游览", "example_en": "We took a guided tour of the museum.", "example_cn": "我们在导游的带领下参观了博物馆。"},
        {"word": "flight", "phonetic": "/flaɪt/", "meaning": "n. 航班", "example_en": "My flight was delayed by two hours.", "example_cn": "我的航班延误了两个小时。"},
        {"word": "passport", "phonetic": "/ˈpɑːspɔːt/", "meaning": "n. 护照", "example_en": "Please show your passport at the checking counter.", "example_cn": "请在值机柜台出示您的护照。"},
        {"word": "bathroom", "phonetic": "/ˈbɑːθruːm/", "meaning": "n. 浴室，洗手间", "example_en": "The bathroom is at the end of the hall.", "example_cn": "洗手间在走廊尽头。"},
        {"word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "meaning": "n. 厨房", "example_en": "Something smells really good in the kitchen.", "example_cn": "厨房里有什么东西闻起来好香。"},
        {"word": "bedroom", "phonetic": "/ˈbedruːm/", "meaning": "n. 卧室", "example_en": "I painted my bedroom walls light blue.", "example_cn": "我把卧室的墙漆成了浅蓝色。"},
        {"word": "towel", "phonetic": "/ˈtaʊəl/", "meaning": "n. 毛巾", "example_en": "Could you bring me a clean towel?", "example_cn": "你能给我拿条干净的毛巾吗？"},
        {"word": "soap", "phonetic": "/səʊp/", "meaning": "n. 肥皂", "example_en": "Wash your hands with soap and water.", "example_cn": "用肥皂和水洗手。"},
        {"word": "brush", "phonetic": "/brʌʃ/", "meaning": "n./v. 刷子；梳理", "example_en": "Remember to brush your teeth before bed.", "example_cn": "记得睡前刷牙。"},
        {"word": "shower", "phonetic": "/ˈʃaʊə(r)/", "meaning": "n. 淋浴", "example_en": "I take a quick shower every morning.", "example_cn": "我每天早上都会快速洗个淋浴。"},
        {"word": "bath", "phonetic": "/bɑːθ/", "meaning": "n. 浴缸，洗澡", "example_en": "She soaked in a hot bath to relax.", "example_cn": "她泡了个热水澡来放松。"},
        {"word": "mirror", "phonetic": "/ˈmɪrə(r)/", "meaning": "n. 镜子", "example_en": "She looked at herself in the mirror.", "example_cn": "她照了照镜子。"},
        {"word": "picture", "phonetic": "/ˈpɪktʃə(r)/", "meaning": "n. 照片，画", "example_en": "Let's take a group picture together.", "example_cn": "我们一起来拍张合影吧。"},
        {"word": "clock", "phonetic": "/klɒk/", "meaning": "n. 时钟", "example_en": "The clock on the wall says it's noon.", "example_cn": "墙上的钟显示现在是中午。"},
        {"word": "radio", "phonetic": "/ˈreɪdiəʊ/", "meaning": "n. 收音机", "example_en": "My grandfather still listens to the radio.", "example_cn": "我爷爷仍然听收音机。"},
        {"word": "television", "phonetic": "/ˈtelɪvɪʒn/", "meaning": "n. 电视机", "example_en": "We watched a movie on the television.", "example_cn": "我们在电视上看了一部电影。"},
        {"word": "sofa", "phonetic": "/ˈsəʊfə/", "meaning": "n. 沙发", "example_en": "He fell asleep on the living room sofa.", "example_cn": "他在客厅的沙发上睡着了。"},
        {"word": "blanket", "phonetic": "/ˈblæŋkɪt/", "meaning": "n. 毯子", "example_en": "Can I have an extra blanket, please?", "example_cn": "请问能给我加一床毯子吗？"},
        {"word": "pillow", "phonetic": "/ˈpɪləʊ/", "meaning": "n. 枕头", "example_en": "This pillow is too soft for my neck.", "example_cn": "这个枕头对我的脖子来说太软了。"},
        {"word": "lock", "phonetic": "/lɒk/", "meaning": "v./n. 锁", "example_en": "Make sure you lock the door when leaving.", "example_cn": "离开时确保把门锁好。"},
        {"word": "open", "phonetic": "/ˈəʊpən/", "meaning": "v. 打开", "example_en": "Please open the window, it's too hot.", "example_cn": "请把窗户打开，太热了。"},
        {"word": "close", "phonetic": "/kləʊz/", "meaning": "v. 关闭", "example_en": "Close your eyes and make a wish.", "example_cn": "闭上眼睛许个愿吧。"},
        {"word": "clean", "phonetic": "/kliːn/", "meaning": "v./adj. 打扫；干净的", "example_en": "I need to clean my room this weekend.", "example_cn": "这周末我需要打扫房间。"},
        {"word": "beef", "phonetic": "/biːf/", "meaning": "n. 牛肉", "example_en": "I ordered a beef steak for dinner.", "example_cn": "我晚餐点了一份牛排。"},
        {"word": "pork", "phonetic": "/pɔːk/", "meaning": "n. 猪肉", "example_en": "We had roast pork with potatoes.", "example_cn": "我们吃了烤猪肉配土豆。"},
        {"word": "chicken", "phonetic": "/ˈtʃɪkɪn/", "meaning": "n. 鸡肉", "example_en": "Fried chicken is his favorite food.", "example_cn": "炸鸡是他最喜欢的食物。"},
        {"word": "vegetable", "phonetic": "/ˈvedʒtəbl/", "meaning": "n. 蔬菜", "example_en": "You should eat more fresh vegetables.", "example_cn": "你应该多吃些新鲜蔬菜。"},
        {"word": "juice", "phonetic": "/dʒuːs/", "meaning": "n. 果汁", "example_en": "A glass of orange juice, please.", "example_cn": "请给我一杯橙汁。"},
        {"word": "soup", "phonetic": "/suːp/", "meaning": "n. 汤", "example_en": "This chicken soup tastes really good.", "example_cn": "这个鸡汤味道真不错。"},
        {"word": "salad", "phonetic": "/ˈsæləd/", "meaning": "n. 沙拉", "example_en": "I'll just have a green salad.", "example_cn": "我只要一份蔬菜沙拉就好。"},
        {"word": "cheese", "phonetic": "/tʃiːz/", "meaning": "n. 奶酪", "example_en": "Do you want some cheese on your pizza?", "example_cn": "你的披萨上要加奶酪吗？"},
        {"word": "butter", "phonetic": "/ˈbʌtə(r)/", "meaning": "n. 黄油", "example_en": "Spread some butter on the toast.", "example_cn": "在吐司上涂点黄油。"},
        {"word": "salt", "phonetic": "/sɔːlt/", "meaning": "n. 盐", "example_en": "The soup needs a little more salt.", "example_cn": "这汤需要再加点盐。"},
        {"word": "sugar", "phonetic": "/ˈʃʊɡə(r)/", "meaning": "n. 糖", "example_en": "I don't put sugar in my coffee.", "example_cn": "我喝咖啡不加糖。"},
        {"word": "sweet", "phonetic": "/swiːt/", "meaning": "adj. 甜的", "example_en": "This chocolate cake is too sweet for me.", "example_cn": "这块巧克力蛋糕对我来说太甜了。"},
        {"word": "sour", "phonetic": "/ˈsaʊə(r)/", "meaning": "adj. 酸的", "example_en": "Lemons have a very sour taste.", "example_cn": "柠檬的味道非常酸。"},
        {"word": "spicy", "phonetic": "/ˈspaɪsi/", "meaning": "adj. 辣的", "example_en": "I love eating spicy Sichuan food.", "example_cn": "我喜欢吃辣的四川菜。"},
        {"word": "bitter", "phonetic": "/ˈbɪtə(r)/", "meaning": "adj. 苦的", "example_en": "Black coffee is a bit bitter.", "example_cn": "黑咖啡有点苦。"},
        {"word": "delicious", "phonetic": "/dɪˈlɪʃəs/", "meaning": "adj. 美味的", "example_en": "Thank you, the meal was absolutely delicious.", "example_cn": "谢谢你，这顿饭绝对美味。"},
        {"word": "fresh", "phonetic": "/freʃ/", "meaning": "adj. 新鲜的", "example_en": "These strawberries are very fresh and juicy.", "example_cn": "这些草莓非常新鲜多汁。"},
        {"word": "hungry", "phonetic": "/ˈhʌŋɡri/", "meaning": "adj. 饥饿的", "example_en": "I am getting hungry, let's grab a bite.", "example_cn": "我开始饿了，我们去吃点东西吧。"},
        {"word": "thirsty", "phonetic": "/ˈθɜːsti/", "meaning": "adj. 口渴的", "example_en": "Drinking soda makes me even more thirsty.", "example_cn": "喝苏打水让我觉得更渴了。"},
        {"word": "cook", "phonetic": "/kʊk/", "meaning": "v. 烹饪", "example_en": "He loves to cook Italian food on weekends.", "example_cn": "他喜欢在周末做意大利菜。"},
        {"word": "week", "phonetic": "/wiːk/", "meaning": "n. 星期", "example_en": "I will see you next week.", "example_cn": "我们下周见。"},
        {"word": "month", "phonetic": "/mʌnθ/", "meaning": "n. 月份", "example_en": "August is the hottest month of the year.", "example_cn": "八月是一年中最热的月份。"},
        {"word": "today", "phonetic": "/təˈdeɪ/", "meaning": "n./adv. 今天", "example_en": "What are you doing later today?", "example_cn": "你今天晚些时候做什么？"},
        {"word": "tomorrow", "phonetic": "/təˈmɒrəʊ/", "meaning": "n./adv. 明天", "example_en": "Tomorrow is a public holiday.", "example_cn": "明天是公共假期。"},
        {"word": "yesterday", "phonetic": "/ˈjestədeɪ/", "meaning": "n./adv. 昨天", "example_en": "It rained all day yesterday.", "example_cn": "昨天几乎下了一整天的雨。"},
        {"word": "weekend", "phonetic": "/ˌwiːkˈend/", "meaning": "n. 周末", "example_en": "Have a great weekend!", "example_cn": "周末愉快！"},
        {"word": "future", "phonetic": "/ˈfjuːtʃə(r)/", "meaning": "n. 未来", "example_en": "Nobody knows what will happen in the future.", "example_cn": "没人知道未来会发生什么。"},
        {"word": "past", "phonetic": "/pɑːst/", "meaning": "n. 过去", "example_en": "Forget the past and move on.", "example_cn": "忘记过去，继续前进吧。"},
        {"word": "always", "phonetic": "/ˈɔːlweɪz/", "meaning": "adv. 总是", "example_en": "She always wakes up at six.", "example_cn": "她总是六点醒来。"},
        {"word": "never", "phonetic": "/ˈnevə(r)/", "meaning": "adv. 从不", "example_en": "I have never seen that movie.", "example_cn": "我从未看过那部电影。"},
        {"word": "sometimes", "phonetic": "/ˈsʌmtaɪmz/", "meaning": "adv. 有时", "example_en": "Sometimes I just want to stay in bed.", "example_cn": "有时候我只想赖在床上。"},
        {"word": "often", "phonetic": "/ˈɒfn/", "meaning": "adv. 经常", "example_en": "How often do you go to the gym?", "example_cn": "你多久去一次健身房？"},
        {"word": "usually", "phonetic": "/ˈjuːʒuəli/", "meaning": "adv. 通常", "example_en": "I usually drink coffee with my breakfast.", "example_cn": "我通常早餐时喝咖啡。"},
        {"word": "early", "phonetic": "/ˈɜːli/", "meaning": "adv. 早的", "example_en": "He arrived at the office very early.", "example_cn": "他很早就到了办公室。"},
        {"word": "late", "phonetic": "/leɪt/", "meaning": "adv. 晚的，迟的", "example_en": "Sorry I'm late, there was heavy traffic.", "example_cn": "抱歉我迟到了，路上很堵。"},
        {"word": "now", "phonetic": "/naʊ/", "meaning": "adv. 现在", "example_en": "We should leave right now.", "example_cn": "我们应该马上离开。"},
        {"word": "then", "phonetic": "/ðen/", "meaning": "adv. 那么；然后", "example_en": "Finish your dinner, then you can watch TV.", "example_cn": "吃完饭，然后你就可以看电视了。"},
        {"word": "before", "phonetic": "/bɪˈfɔː(r)/", "meaning": "prep. 在...之前", "example_en": "Wash your hands before you eat.", "example_cn": "吃饭前洗手。"},
        {"word": "after", "phonetic": "/ˈɑːftə(r)/", "meaning": "prep. 在...之后", "example_en": "Let's go for a walk after lunch.", "example_cn": "午饭后我们去散步吧。"},
        {"word": "time", "phonetic": "/taɪm/", "meaning": "n. 时间", "example_en": "What time does the movie start?", "example_cn": "电影几点开始？"}
    ],

    # -------------------------------------------------------------
    # Level 2: 海外生存 - 餐饮、出行与方向 - 50词 (原 Level 4)
    # -------------------------------------------------------------
    2: [
        {"word": "receipt", "phonetic": "/rɪˈsiːt/", "meaning": "n. 收据，小票", "example_en": "Do you need a receipt?", "example_cn": "你需要收据吗？"},
        {"word": "order", "phonetic": "/ˈɔːrdər/", "meaning": "v. 点餐", "example_en": "Are you ready to order?", "example_cn": "您准备好点餐了吗？"},
        {"word": "takeout", "phonetic": "/ˈteɪkaʊt/", "meaning": "n. 外卖，打包", "example_en": "I'd like to get this for takeout.", "example_cn": "我想把这个打包带走。"},
        {"word": "cashier", "phonetic": "/kæˈʃɪr/", "meaning": "n. 收银员", "example_en": "Please pay the cashier.", "example_cn": "请去收银员那里付款。"},
        {"word": "discount", "phonetic": "/ˈdɪskaʊnt/", "meaning": "n. 折扣", "example_en": "Is there a discount for students?", "example_cn": "学生有打折吗？"},
        {"word": "menu", "phonetic": "/ˈmenjuː/", "meaning": "n. 菜单", "example_en": "Can I see the menu, please?", "example_cn": "能给我看看菜单吗？"},
        {"word": "bill", "phonetic": "/bɪl/", "meaning": "n. 账单", "example_en": "Could we have the bill, please?", "example_cn": "请买单。"},
        {"word": "tip", "phonetic": "/tɪp/", "meaning": "n. 小费", "example_en": "Don't forget to leave a tip.", "example_cn": "别忘了留小费。"},
        {"word": "napkin", "phonetic": "/ˈnæpkɪn/", "meaning": "n. 餐巾纸", "example_en": "Could I get some extra napkins?", "example_cn": "能多给我几张餐巾纸吗？"},
        {"word": "fork", "phonetic": "/fɔːrk/", "meaning": "n. 叉子", "example_en": "I dropped my fork.", "example_cn": "我的叉子掉了。"},
        {"word": "knife", "phonetic": "/naɪf/", "meaning": "n. 刀", "example_en": "I need a knife to cut the steak.", "example_cn": "我需要一把刀切牛排。"},
        {"word": "spoon", "phonetic": "/spuːn/", "meaning": "n. 勺子", "example_en": "Can I have a spoon for my soup?", "example_cn": "能给我把喝汤的勺子吗？"},
        {"word": "plate", "phonetic": "/pleɪt/", "meaning": "n. 盘子", "example_en": "Could we get an extra plate?", "example_cn": "能再给我们一个盘子吗？"},
        {"word": "delicious", "phonetic": "/dɪˈlɪʃəs/", "meaning": "adj. 美味的", "example_en": "The food here is delicious.", "example_cn": "这里的食物很美味。"},
        {"word": "spicy", "phonetic": "/ˈspaɪsi/", "meaning": "adj. 辣的", "example_en": "I love eating spicy food.", "example_cn": "我喜欢吃辣的食物。"},
        {"word": "sweet", "phonetic": "/swiːt/", "meaning": "adj. 甜的", "example_en": "This cake is too sweet.", "example_cn": "这块蛋糕太甜了。"},
        {"word": "sour", "phonetic": "/ˈsaʊər/", "meaning": "adj. 酸的", "example_en": "Lemons are very sour.", "example_cn": "柠檬非常酸。"},
        {"word": "bitter", "phonetic": "/ˈbɪtər/", "meaning": "adj. 苦的", "example_en": "Black coffee is bitter.", "example_cn": "黑咖啡很苦。"},
        {"word": "salty", "phonetic": "/ˈsɔːlti/", "meaning": "adj. 咸的", "example_en": "The soup is a bit salty.", "example_cn": "这汤有点咸。"},
        {"word": "vegetarian", "phonetic": "/ˌvedʒəˈteriən/", "meaning": "adj. 素食的", "example_en": "Do you have vegetarian options?", "example_cn": "你们有素食的选择吗？"},
        {"word": "allergy", "phonetic": "/ˈælərdʒi/", "meaning": "n. 过敏", "example_en": "I have an allergy to peanuts.", "example_cn": "我对花生过敏。"},
        {"word": "water", "phonetic": "/ˈwɔːtər/", "meaning": "n. 水", "example_en": "Can I get a glass of water?", "example_cn": "能给我一杯水吗？"},
        {"word": "ice", "phonetic": "/aɪs/", "meaning": "n. 冰", "example_en": "No ice, please.", "example_cn": "请去冰。"},
        {"word": "refill", "phonetic": "/ˈriːfɪl/", "meaning": "n./v. 续杯", "example_en": "Are refills free?", "example_cn": "续杯是免费的吗？"},
        {"word": "total", "phonetic": "/ˈtoʊtl/", "meaning": "n. 总计", "example_en": "What is the total cost?", "example_cn": "总费用是多少？"},
        {"word": "cash", "phonetic": "/kæʃ/", "meaning": "n. 现金", "example_en": "I will pay in cash.", "example_cn": "我会付现金。"},
        {"word": "credit", "phonetic": "/ˈkredɪt/", "meaning": "n. 信用卡", "example_en": "Do you take credit cards?", "example_cn": "你们收信用卡吗？"},
        {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "n. 零钱", "example_en": "Keep the change.", "example_cn": "不用找零了。"},
        {"word": "airport", "phonetic": "/ˈerpɔːrt/", "meaning": "n. 机场", "example_en": "How far is the airport?", "example_cn": "机场有多远？"},
        {"word": "flight", "phonetic": "/flaɪt/", "meaning": "n. 航班", "example_en": "My flight is delayed.", "example_cn": "我的航班延误了。"},
        {"word": "luggage", "phonetic": "/ˈlʌɡɪdʒ/", "meaning": "n. 行李", "example_en": "Where can I pick up my luggage?", "example_cn": "我在哪里拿行李？"},
        {"word": "passport", "phonetic": "/ˈpæspɔːrt/", "meaning": "n. 护照", "example_en": "Here is my passport.", "example_cn": "这是我的护照。"},
        {"word": "visa", "phonetic": "/ˈviːzə/", "meaning": "n. 签证", "example_en": "I need a student visa.", "example_cn": "我需要学生签证。"},
        {"word": "gate", "phonetic": "/ɡeɪt/", "meaning": "n. 登机口", "example_en": "Which gate is for flight 802?", "example_cn": "802航班在哪个登机口？"},
        {"word": "board", "phonetic": "/bɔːrd/", "meaning": "v. 登机", "example_en": "It is time to board the plane.", "example_cn": "该登机了。"},
        {"word": "delay", "phonetic": "/dɪˈleɪ/", "meaning": "v./n. 延误", "example_en": "The train has a short delay.", "example_cn": "火车有短暂的延误。"},
        {"word": "cancel", "phonetic": "/ˈkænsəl/", "meaning": "v. 取消", "example_en": "The meeting was canceled.", "example_cn": "会议被取消了。"},
        {"word": "arrive", "phonetic": "/əˈraɪv/", "meaning": "v. 到达", "example_en": "What time will we arrive?", "example_cn": "我们几点到达？"},
        {"word": "depart", "phonetic": "/dɪˈpɑːrt/", "meaning": "v. 离开，出发", "example_en": "The bus departs at 9 AM.", "example_cn": "巴士早上9点出发。"},
        {"word": "taxi", "phonetic": "/ˈtæksi/", "meaning": "n. 出租车", "example_en": "Let's call a taxi.", "example_cn": "我们叫辆出租车吧。"},
        {"word": "subway", "phonetic": "/ˈsʌbweɪ/", "meaning": "n. 地铁", "example_en": "I take the subway to work.", "example_cn": "我坐地铁去上班。"},
        {"word": "station", "phonetic": "/ˈsteɪʃn/", "meaning": "n. 车站", "example_en": "Turn left at the train station.", "example_cn": "在火车站左转。"},
        {"word": "ticket", "phonetic": "/ˈtɪkɪt/", "meaning": "n. 票", "example_en": "Where can I buy a ticket?", "example_cn": "我在哪里可以买票？"},
        {"word": "map", "phonetic": "/mæp/", "meaning": "n. 地图", "example_en": "Can you show me on the map?", "example_cn": "你能在地图上指给我看吗？"},
        {"word": "street", "phonetic": "/striːt/", "meaning": "n. 街道", "example_en": "Go down this street.", "example_cn": "沿着这条街走。"},
        {"word": "corner", "phonetic": "/ˈkɔːrnər/", "meaning": "n. 角落，路口", "example_en": "The shop is on the corner.", "example_cn": "商店在街角。"},
        {"word": "straight", "phonetic": "/streɪt/", "meaning": "adv. 直走", "example_en": "Go straight ahead.", "example_cn": "一直往前走。"},
        {"word": "left", "phonetic": "/left/", "meaning": "n./adv. 左边", "example_en": "Turn left at the next light.", "example_cn": "在下一个红绿灯左转。"},
        {"word": "right", "phonetic": "/raɪt/", "meaning": "n./adv. 右边", "example_en": "It is on your right.", "example_cn": "它在你的右边。"},
        {"word": "crosswalk", "phonetic": "/ˈkrɔːswɔːk/", "meaning": "n. 人行横道", "example_en": "Always use the crosswalk.", "example_cn": "请务必走人行横道。"}
    ],

    # -------------------------------------------------------------
    # Level 3: 海外生存 - 购物、居住与求助 - 50词 (原 Level 5)
    # -------------------------------------------------------------
    3: [
        {"word": "restroom", "phonetic": "/ˈrestrʊm/", "meaning": "n. 洗手间", "example_en": "Where is the restroom?", "example_cn": "请问洗手间在哪里？"},
        {"word": "pharmacy", "phonetic": "/ˈfɑːrməsi/", "meaning": "n. 药店", "example_en": "Is there a pharmacy nearby?", "example_cn": "附近有药店吗？"},
        {"word": "rent", "phonetic": "/rent/", "meaning": "n. 租金", "example_en": "How much is the rent?", "example_cn": "租金是多少？"},
        {"word": "appointment", "phonetic": "/əˈpɔɪntmənt/", "meaning": "n. 预约", "example_en": "I have a doctor's appointment.", "example_cn": "我有个看医生的预约。"},
        {"word": "emergency", "phonetic": "/ɪˈmɜːrdʒənsi/", "meaning": "n. 紧急情况", "example_en": "This is an emergency!", "example_cn": "这是紧急情况！"},
        {"word": "hospital", "phonetic": "/ˈhɑːspɪtl/", "meaning": "n. 医院", "example_en": "Take him to the hospital.", "example_cn": "送他去医院。"},
        {"word": "doctor", "phonetic": "/ˈdɑːktər/", "meaning": "n. 医生", "example_en": "I need to see a doctor.", "example_cn": "我需要看医生。"},
        {"word": "pain", "phonetic": "/peɪn/", "meaning": "n. 疼痛", "example_en": "I have pain in my chest.", "example_cn": "我胸口疼。"},
        {"word": "fever", "phonetic": "/ˈfiːvər/", "meaning": "n. 发烧", "example_en": "He has a high fever.", "example_cn": "他发高烧了。"},
        {"word": "cough", "phonetic": "/kɔːf/", "meaning": "n./v. 咳嗽", "example_en": "I have a bad cough.", "example_cn": "我咳得很厉害。"},
        {"word": "medicine", "phonetic": "/ˈmedɪsn/", "meaning": "n. 药", "example_en": "Take this medicine twice a day.", "example_cn": "这个药一天吃两次。"},
        {"word": "pill", "phonetic": "/pɪl/", "meaning": "n. 药丸", "example_en": "Swallow the pill with water.", "example_cn": "用水把药片吞下。"},
        {"word": "police", "phonetic": "/pəˈliːs/", "meaning": "n. 警察", "example_en": "Call the police!", "example_cn": "快报警！"},
        {"word": "help", "phonetic": "/help/", "meaning": "v./n. 帮助", "example_en": "Can you help me?", "example_cn": "你能帮帮我吗？"},
        {"word": "safe", "phonetic": "/seɪf/", "meaning": "adj. 安全的", "example_en": "Is it safe to walk here at night?", "example_cn": "晚上在这里走安全吗？"},
        {"word": "dangerous", "phonetic": "/ˈdeɪndʒərəs/", "meaning": "adj. 危险的", "example_en": "The road is very dangerous.", "example_cn": "这条路非常危险。"},
        {"word": "lost", "phonetic": "/lɔːst/", "meaning": "adj. 迷路的，丢失的", "example_en": "I am lost. Can you help me?", "example_cn": "我迷路了。你能帮我吗？"},
        {"word": "found", "phonetic": "/faʊnd/", "meaning": "adj. 找到的", "example_en": "I found my keys.", "example_cn": "我找到我的钥匙了。"},
        {"word": "wallet", "phonetic": "/ˈwɑːlɪt/", "meaning": "n. 钱包", "example_en": "Someone stole my wallet.", "example_cn": "有人偷了我的钱包。"},
        {"word": "phone", "phonetic": "/foʊn/", "meaning": "n. 电话，手机", "example_en": "My phone is out of service.", "example_cn": "我的手机没信号。"},
        {"word": "battery", "phonetic": "/ˈbætəri/", "meaning": "n. 电池", "example_en": "My phone battery is low.", "example_cn": "我手机快没电了。"},
        {"word": "charger", "phonetic": "/ˈtʃɑːrdʒər/", "meaning": "n. 充电器", "example_en": "Do you have a phone charger?", "example_cn": "你有手机充电器吗？"},
        {"word": "plug", "phonetic": "/plʌɡ/", "meaning": "n. 插头", "example_en": "Where is the plug?", "example_cn": "插头在哪里？"},
        {"word": "outlet", "phonetic": "/ˈaʊtlet/", "meaning": "n. 插座", "example_en": "Is there an outlet here?", "example_cn": "这里有电源插座吗？"},
        {"word": "store", "phonetic": "/stɔːr/", "meaning": "n. 商店", "example_en": "The store is closed today.", "example_cn": "商店今天关门。"},
        {"word": "open", "phonetic": "/ˈoʊpən/", "meaning": "adj. 营业的", "example_en": "Are you open on Sundays?", "example_cn": "你们星期天营业吗？"},
        {"word": "closed", "phonetic": "/kloʊzd/", "meaning": "adj. 关闭的", "example_en": "Sorry, we are closed.", "example_cn": "抱歉，我们关门了。"},
        {"word": "sale", "phonetic": "/seɪl/", "meaning": "n. 特卖", "example_en": "These shoes are on sale.", "example_cn": "这双鞋在打折。"},
        {"word": "price", "phonetic": "/praɪs/", "meaning": "n. 价格", "example_en": "What is the price of this?", "example_cn": "这个多少钱？"},
        {"word": "cheap", "phonetic": "/tʃiːp/", "meaning": "adj. 便宜的", "example_en": "It is very cheap.", "example_cn": "这个很便宜。"},
        {"word": "expensive", "phonetic": "/ɪkˈspensɪv/", "meaning": "adj. 贵的", "example_en": "That is too expensive for me.", "example_cn": "那个对我来说太贵了。"},
        {"word": "size", "phonetic": "/saɪz/", "meaning": "n. 尺寸，尺码", "example_en": "Do you have this in a larger size?", "example_cn": "你们有大一号的吗？"},
        {"word": "fit", "phonetic": "/fɪt/", "meaning": "v. 合身", "example_en": "This shirt doesn't fit me.", "example_cn": "这件衬衫我穿不合身。"},
        {"word": "try", "phonetic": "/traɪ/", "meaning": "v. 试穿", "example_en": "Can I try this on?", "example_cn": "我能试穿一下这个吗？"},
        {"word": "color", "phonetic": "/ˈkʌlər/", "meaning": "n. 颜色", "example_en": "Do you have this in a different color?", "example_cn": "这个有别的颜色吗？"},
        {"word": "refund", "phonetic": "/ˈriːfʌnd/", "meaning": "n. 退款", "example_en": "Can I get a refund?", "example_cn": "我能退款吗？"},
        {"word": "return", "phonetic": "/rɪˈtɜːrn/", "meaning": "v. 退货", "example_en": "I want to return this shirt.", "example_cn": "我想退掉这件衬衫。"},
        {"word": "exchange", "phonetic": "/ɪksˈtʃeɪndʒ/", "meaning": "v. 换货", "example_en": "Can I exchange it for a smaller one?", "example_cn": "我能换个小点的吗？"},
        {"word": "elevator", "phonetic": "/ˈelɪveɪtər/", "meaning": "n. 电梯", "example_en": "Take the elevator to the 3rd floor.", "example_cn": "坐电梯到三楼。"},
        {"word": "stairs", "phonetic": "/sterz/", "meaning": "n. 楼梯", "example_en": "The stairs are over there.", "example_cn": "楼梯在那边。"},
        {"word": "entrance", "phonetic": "/ˈentrəns/", "meaning": "n. 入口", "example_en": "Meet me at the main entrance.", "example_cn": "在正门入口见。"},
        {"word": "exit", "phonetic": "/ˈeɡzɪt/", "meaning": "n. 出口", "example_en": "Where is the emergency exit?", "example_cn": "紧急出口在哪里？"},
        {"word": "push", "phonetic": "/pʊʃ/", "meaning": "v. 推", "example_en": "Push the door open.", "example_cn": "把门推开。"},
        {"word": "pull", "phonetic": "/pʊl/", "meaning": "v. 拉", "example_en": "You need to pull to open it.", "example_cn": "你需要拉开它。"},
        {"word": "apartment", "phonetic": "/əˈpɑːrtmənt/", "meaning": "n. 公寓", "example_en": "I live in a small apartment.", "example_cn": "我住在一个小公寓里。"},
        {"word": "key", "phonetic": "/kiː/", "meaning": "n. 钥匙", "example_en": "I lost my room key.", "example_cn": "我把房间钥匙丢了。"},
        {"word": "lock", "phonetic": "/lɑːk/", "meaning": "v./n. 锁", "example_en": "Please lock the door when you leave.", "example_cn": "离开时请锁门。"},
        {"word": "neighbor", "phonetic": "/ˈneɪbər/", "meaning": "n. 邻居", "example_en": "My neighbor is very friendly.", "example_cn": "我的邻居很友好。"},
        {"word": "loud", "phonetic": "/laʊd/", "meaning": "adj. 吵闹的", "example_en": "The music is too loud.", "example_cn": "音乐太吵了。"},
        {"word": "quiet", "phonetic": "/ˈkwaɪət/", "meaning": "adj. 安静的", "example_en": "Please be quiet in the library.", "example_cn": "在图书馆请保持安静。"}
    ]
} # ⚠️ 修复点：在这里补上了缺失的闭合大括号！

# 将剩余的关卡（4-20）暂时先用 Level 3 填充，防止数组越界报错
for lvl in range(4, 21):
    GLOBAL_VOCAB_DB[lvl] = list(GLOBAL_VOCAB_DB[3])
