# vocab_data.py
# 真实难度递进词库：每个词独立造句，拒绝模板句

GLOBAL_VOCAB_DB = {
    # -------------------------------------------------------------
    # Level 1: 职场学习、城市交通、食物味道与时间频率 - 100词
    # -------------------------------------------------------------
    1: [
        {"word": "office", "phonetic": "/ˈɒfɪs/", "meaning": "n. 办公室", "example_en": "I left my umbrella in the office.", "example_cn": "我把伞落在办公室了。"},
        {"word": "boss", "phonetic": "/bɒs/", "meaning": "n. 老板", "example_en": "My boss gave me a new project today.", "example_cn": "我老板今天交给我一个新项目。"},
        {"word": "job", "phonetic": "/dʒɒb/", "meaning": "n. 工作", "example_en": "Finding a good job is not easy.", "example_cn": "找一份好工作并不容易。"},
        {"word": "meeting", "phonetic": "/ˈmiːtɪŋ/", "meaning": "n. 会议", "example_en": "We have a team meeting at 10 AM.", "example_cn": "我们上午10点有个团队会议。"},
        {"word": "break", "phonetic": "/breɪk/", "meaning": "n. 休息", "example_en": "Let's take a ten-minute break.", "example_cn": "我们休息十分钟吧。"},
        {"word": "student", "phonetic": "/ˈstjuːdnt/", "meaning": "n. 学生", "example_en": "The student asked the teacher a question.", "example_cn": "那个学生问了老师一个问题。"},
        {"word": "class", "phonetic": "/klɑːs/", "meaning": "n. 课程；班级", "example_en": "I was late for my English class.", "example_cn": "我的英语课迟到了。"},
        {"word": "homework", "phonetic": "/ˈhəʊmwɜːk/", "meaning": "n. 家庭作业", "example_en": "Did you finish your math homework?", "example_cn": "你做完数学作业了吗？"},
        {"word": "test", "phonetic": "/test/", "meaning": "n. 测试，考试", "example_en": "I need to study for the driving test.", "example_cn": "我需要为驾照考试做准备。"},
        {"word": "pass", "phonetic": "/pɑːs/", "meaning": "v. 通过", "example_en": "She studied hard and passed the exam.", "example_cn": "她努力学习并通过了考试。"},
        {"word": "fail", "phonetic": "/feɪl/", "meaning": "v. 失败，不及格", "example_en": "Don't worry if you fail, just try again.", "example_cn": "如果不及格别担心，再试一次就好。"},
        {"word": "easy", "phonetic": "/ˈiːzi/", "meaning": "adj. 容易的", "example_en": "This puzzle is too easy for me.", "example_cn": "这个谜题对我来说太简单了。"},
        {"word": "hard", "phonetic": "/hɑːd/", "meaning": "adj. 困难的；努力的", "example_en": "He works hard to support his family.", "example_cn": "他努力工作来养家。"},
        {"word": "learn", "phonetic": "/lɜːn/", "meaning": "v. 学习", "example_en": "I want to learn how to play the guitar.", "example_cn": "我想学习弹吉他。"},
        {"word": "study", "phonetic": "/ˈstʌdi/", "meaning": "v. 学习，研究", "example_en": "We study in the library every afternoon.", "example_cn": "我们每天下午在图书馆学习。"},
        {"word": "use", "phonetic": "/juːz/", "meaning": "v. 使用", "example_en": "Can I use your phone for a second?", "example_cn": "我能用一下你的手机吗？"},
        {"word": "try", "phonetic": "/traɪ/", "meaning": "v. 尝试", "example_en": "You should try this delicious cake.", "example_cn": "你应该尝尝这块美味的蛋糕。"},
        {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "v. 改变，更换", "example_en": "I need to change my clothes before the party.", "example_cn": "派对前我需要换身衣服。"},
        {"word": "wait", "phonetic": "/weɪt/", "meaning": "v. 等待", "example_en": "Please wait for me at the entrance.", "example_cn": "请在入口处等我。"},
        {"word": "help", "phonetic": "/help/", "meaning": "v./n. 帮助", "example_en": "Thank you so much for your help.", "example_cn": "非常感谢你的帮助。"},
        {"word": "street", "phonetic": "/striːt/", "meaning": "n. 街道", "example_en": "Look both ways before crossing the street.", "example_cn": "过马路前要注意两边。"},
        {"word": "avenue", "phonetic": "/ˈævənjuː/", "meaning": "n. 大道", "example_en": "Their shop is located on Fifth Avenue.", "example_cn": "他们的店位于第五大道。"},
        {"word": "traffic", "phonetic": "/ˈtræfɪk/", "meaning": "n. 交通", "example_en": "The traffic is always terrible in the morning.", "example_cn": "早上的交通总是很糟糕。"},
        {"word": "bridge", "phonetic": "/brɪdʒ/", "meaning": "n. 桥梁", "example_en": "We drove across the golden bridge.", "example_cn": "我们开车驶过了那座金色的桥。"},
        {"word": "corner", "phonetic": "/ˈkɔːnə(r)/", "meaning": "n. 角落，拐角", "example_en": "The coffee shop is right around the corner.", "example_cn": "那家咖啡店就在拐角处。"},
        {"word": "map", "phonetic": "/mæp/", "meaning": "n. 地图", "example_en": "Let me check the map on my phone.", "example_cn": "让我查一下手机上的地图。"},
        {"word": "block", "phonetic": "/blɒk/", "meaning": "n. 街区", "example_en": "Walk two blocks and turn left.", "example_cn": "走两个街区然后左转。"},
        {"word": "subway", "phonetic": "/ˈsʌbweɪ/", "meaning": "n. 地铁", "example_en": "Taking the subway is faster than taking a taxi.", "example_cn": "坐地铁比打车快。"},
        {"word": "bicycle", "phonetic": "/ˈbaɪsɪkl/", "meaning": "n. 自行车", "example_en": "She rides her bicycle to work every day.", "example_cn": "她每天骑自行车上班。"},
        {"word": "drive", "phonetic": "/draɪv/", "meaning": "v. 驾驶", "example_en": "It takes an hour to drive to the airport.", "example_cn": "开车去机场需要一个小时。"},
        {"word": "ride", "phonetic": "/raɪd/", "meaning": "v. 骑", "example_en": "He likes to ride a horse on the farm.", "example_cn": "他喜欢在农场里骑马。"},
        {"word": "stop", "phonetic": "/stɒp/", "meaning": "v. 停止", "example_en": "The bus will stop at the next station.", "example_cn": "公交车将在下一站停车。"},
        {"word": "fast", "phonetic": "/fɑːst/", "meaning": "adj./adv. 快的", "example_en": "Don't drive so fast, it's dangerous.", "example_cn": "别开这么快，很危险。"},
        {"word": "slow", "phonetic": "/sləʊ/", "meaning": "adj. 慢的", "example_en": "The internet connection is very slow today.", "example_cn": "今天的网络连接非常慢。"},
        {"word": "trip", "phonetic": "/trɪp/", "meaning": "n. 旅行", "example_en": "How was your business trip to London?", "example_cn": "你去伦敦的出差顺利吗？"},
        {"word": "vacation", "phonetic": "/vəˈkeɪʃn/", "meaning": "n. 假期", "example_en": "I need a long vacation to relax.", "example_cn": "我需要一个长假来放松一下。"},
        {"word": "guide", "phonetic": "/ɡaɪd/", "meaning": "n. 导游；指南", "example_en": "Our tour guide was very friendly and helpful.", "example_cn": "我们的导游非常友好并且乐于助人。"},
        {"word": "tour", "phonetic": "/tʊə(r)/", "meaning": "n. 参观，游览", "example_en": "We took a guided tour of the museum.", "example_cn": "我们在导游的带领下参观了博物馆。"},
        {"word": "flight", "phonetic": "/flaɪt/", "meaning": "n. 航班", "example_en": "My flight was delayed by two hours.", "example_cn": "我的航班延误了两个小时。"},
        {"word": "passport", "phonetic": "/ˈpɑːspɔːt/", "meaning": "n. 护照", "example_en": "Please show your passport at the checking counter.", "example_cn": "请在值机柜台出示您的护照。"},
        {"word": "bathroom", "phonetic": "/ˈbɑːθruːm/", "meaning": "n. 浴室，洗手间", "example_en": "The bathroom is at the end of the hall.", "example_cn": "洗手间在走廊尽头。"},
        {"word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "meaning": "n. 厨房", "example_en": "Something smells really good in the kitchen.", "example_cn": "厨房里有什么东西闻起来好香。"},
        {"word": "bedroom", "phonetic": "/ˈbedruːm/", "meaning": "n. 卧室", "example_en": "I painted my bedroom walls light blue.", "example_cn": "我把卧室的墙漆成了浅蓝色。"},
        {"word": "towel", "phonetic": "/ˈtaʊəl/", "meaning": "n. 毛巾", "example_en": "Could you bring me a clean towel?", "example_cn": "你能给我拿条干净的毛巾吗？"},
        {"word": "soap", "phonetic": "/səʊp/", "meaning": "n. 肥皂", "example_en": "Wash your hands with soap and water.", "example_cn": "用肥皂和水洗手。"},
        {"word": "brush", "phonetic": "/brʌʃ/", "meaning": "n./v. 刷子；梳理", "example_en": "Remember to brush your teeth before bed.", "example_cn": "记得睡前刷牙。"},
        {"word": "shower", "phonetic": "/ˈʃaʊə(r)/", "meaning": "n. 淋浴", "example_en": "I take a quick shower every morning.", "example_cn": "我每天早上都会快速洗个淋浴。"},
        {"word": "bath", "phonetic": "/bɑːθ/", "meaning": "n. 浴缸，洗澡", "example_en": "She soaked in a hot bath to relax.", "example_cn": "她泡了个热水澡来放松。"},
        {"word": "mirror", "phonetic": "/ˈmɪrə(r)/", "meaning": "n. 镜子", "example_en": "She looked at herself in the mirror.", "example_cn": "她照了照镜子。"},
        {"word": "picture", "phonetic": "/ˈpɪktʃə(r)/", "meaning": "n. 照片，画", "example_en": "Let's take a group picture together.", "example_cn": "我们一起来拍张合影吧。"},
        {"word": "clock", "phonetic": "/klɒk/", "meaning": "n. 时钟", "example_en": "The clock on the wall says it's noon.", "example_cn": "墙上的钟显示现在是中午。"},
        {"word": "radio", "phonetic": "/ˈreɪdiəʊ/", "meaning": "n. 收音机", "example_en": "My grandfather still listens to the radio.", "example_cn": "我爷爷仍然听收音机。"},
        {"word": "television", "phonetic": "/ˈtelɪvɪʒn/", "meaning": "n. 电视机", "example_en": "We watched a movie on the television.", "example_cn": "我们在电视上看了一部电影。"},
        {"word": "sofa", "phonetic": "/ˈsəʊfə/", "meaning": "n. 沙发", "example_en": "He fell asleep on the living room sofa.", "example_cn": "他在客厅的沙发上睡着了。"},
        {"word": "blanket", "phonetic": "/ˈblæŋkɪt/", "meaning": "n. 毯子", "example_en": "Can I have an extra blanket, please?", "example_cn": "请问能给我加一床毯子吗？"},
        {"word": "pillow", "phonetic": "/ˈpɪləʊ/", "meaning": "n. 枕头", "example_en": "This pillow is too soft for my neck.", "example_cn": "这个枕头对我的脖子来说太软了。"},
        {"word": "lock", "phonetic": "/lɒk/", "meaning": "v./n. 锁", "example_en": "Make sure you lock the door when leaving.", "example_cn": "离开时确保把门锁好。"},
        {"word": "open", "phonetic": "/ˈəʊpən/", "meaning": "v. 打开", "example_en": "Please open the window, it's too hot.", "example_cn": "请把窗户打开，太热了。"},
        {"word": "close", "phonetic": "/kləʊz/", "meaning": "v. 关闭", "example_en": "Close your eyes and make a wish.", "example_cn": "闭上眼睛许个愿吧。"},
        {"word": "clean", "phonetic": "/kliːn/", "meaning": "v./adj. 打扫；干净的", "example_en": "I need to clean my room this weekend.", "example_cn": "这周末我需要打扫房间。"},
        {"word": "beef", "phonetic": "/biːf/", "meaning": "n. 牛肉", "example_en": "I ordered a beef steak for dinner.", "example_cn": "我晚餐点了一份牛排。"},
        {"word": "pork", "phonetic": "/pɔːk/", "meaning": "n. 猪肉", "example_en": "We had roast pork with potatoes.", "example_cn": "我们吃了烤猪肉配土豆。"},
        {"word": "chicken", "phonetic": "/ˈtʃɪkɪn/", "meaning": "n. 鸡肉", "example_en": "Fried chicken is his favorite food.", "example_cn": "炸鸡是他最喜欢的食物。"},
        {"word": "vegetable", "phonetic": "/ˈvedʒtəbl/", "meaning": "n. 蔬菜", "example_en": "You should eat more fresh vegetables.", "example_cn": "你应该多吃些新鲜蔬菜。"},
        {"word": "juice", "phonetic": "/dʒuːs/", "meaning": "n. 果汁", "example_en": "A glass of orange juice, please.", "example_cn": "请给我一杯橙汁。"},
        {"word": "soup", "phonetic": "/suːp/", "meaning": "n. 汤", "example_en": "This chicken soup tastes really good.", "example_cn": "这个鸡汤味道真不错。"},
        {"word": "salad", "phonetic": "/ˈsæləd/", "meaning": "n. 沙拉", "example_en": "I'll just have a green salad.", "example_cn": "我只要一份蔬菜沙拉就好。"},
        {"word": "cheese", "phonetic": "/tʃiːz/", "meaning": "n. 奶酪", "example_en": "Do you want some cheese on your pizza?", "example_cn": "你的披萨上要加奶酪吗？"},
        {"word": "butter", "phonetic": "/ˈbʌtə(r)/", "meaning": "n. 黄油", "example_en": "Spread some butter on the toast.", "example_cn": "在吐司上涂点黄油。"},
        {"word": "salt", "phonetic": "/sɔːlt/", "meaning": "n. 盐", "example_en": "The soup needs a little more salt.", "example_cn": "这汤需要再加点盐。"},
        {"word": "sugar", "phonetic": "/ˈʃʊɡə(r)/", "meaning": "n. 糖", "example_en": "I don't put sugar in my coffee.", "example_cn": "我喝咖啡不加糖。"},
        {"word": "sweet", "phonetic": "/swiːt/", "meaning": "adj. 甜的", "example_en": "This chocolate cake is too sweet for me.", "example_cn": "这块巧克力蛋糕对我来说太甜了。"},
        {"word": "sour", "phonetic": "/ˈsaʊə(r)/", "meaning": "adj. 酸的", "example_en": "Lemons have a very sour taste.", "example_cn": "柠檬的味道非常酸。"},
        {"word": "spicy", "phonetic": "/ˈspaɪsi/", "meaning": "adj. 辣的", "example_en": "I love eating spicy Sichuan food.", "example_cn": "我喜欢吃辣的四川菜。"},
        {"word": "bitter", "phonetic": "/ˈbɪtə(r)/", "meaning": "adj. 苦的", "example_en": "Black coffee is a bit bitter.", "example_cn": "黑咖啡有点苦。"},
        {"word": "delicious", "phonetic": "/dɪˈlɪʃəs/", "meaning": "adj. 美味的", "example_en": "Thank you, the meal was absolutely delicious.", "example_cn": "谢谢你，这顿饭绝对美味。"},
        {"word": "fresh", "phonetic": "/freʃ/", "meaning": "adj. 新鲜的", "example_en": "These strawberries are very fresh and juicy.", "example_cn": "这些草莓非常新鲜多汁。"},
        {"word": "hungry", "phonetic": "/ˈhʌŋɡri/", "meaning": "adj. 饥饿的", "example_en": "I am getting hungry, let's grab a bite.", "example_cn": "我开始饿了，我们去吃点东西吧。"},
        {"word": "thirsty", "phonetic": "/ˈθɜːsti/", "meaning": "adj. 口渴的", "example_en": "Drinking soda makes me even more thirsty.", "example_cn": "喝苏打水让我觉得更渴了。"},
        {"word": "cook", "phonetic": "/kʊk/", "meaning": "v. 烹饪", "example_en": "He loves to cook Italian food on weekends.", "example_cn": "他喜欢在周末做意大利菜。"},
        {"word": "week", "phonetic": "/wiːk/", "meaning": "n. 星期", "example_en": "I will see you next week.", "example_cn": "我们下周见。"},
        {"word": "month", "phonetic": "/mʌnθ/", "meaning": "n. 月份", "example_en": "August is the hottest month of the year.", "example_cn": "八月是一年中最热的月份。"},
        {"word": "today", "phonetic": "/təˈdeɪ/", "meaning": "n./adv. 今天", "example_en": "What are you doing later today?", "example_cn": "你今天晚些时候做什么？"},
        {"word": "tomorrow", "phonetic": "/təˈmɒrəʊ/", "meaning": "n./adv. 明天", "example_en": "Tomorrow is a public holiday.", "example_cn": "明天是公共假期。"},
        {"word": "yesterday", "phonetic": "/ˈjestədeɪ/", "meaning": "n./adv. 昨天", "example_en": "It rained all day yesterday.", "example_cn": "昨天几乎下了一整天的雨。"},
        {"word": "weekend", "phonetic": "/ˌwiːkˈend/", "meaning": "n. 周末", "example_en": "Have a great weekend!", "example_cn": "周末愉快！"},
        {"word": "future", "phonetic": "/ˈfjuːtʃə(r)/", "meaning": "n. 未来", "example_en": "Nobody knows what will happen in the future.", "example_cn": "没人知道未来会发生什么。"},
        {"word": "past", "phonetic": "/pɑːst/", "meaning": "n. 过去", "example_en": "Forget the past and move on.", "example_cn": "忘记过去，继续前进吧。"},
        {"word": "always", "phonetic": "/ˈɔːlweɪz/", "meaning": "adv. 总是", "example_en": "She always wakes up at six.", "example_cn": "她总是六点醒来。"},
        {"word": "never", "phonetic": "/ˈnevə(r)/", "meaning": "adv. 从不", "example_en": "I have never seen that movie.", "example_cn": "我从未看过那部电影。"},
        {"word": "sometimes", "phonetic": "/ˈsʌmtaɪmz/", "meaning": "adv. 有时", "example_en": "Sometimes I just want to stay in bed.", "example_cn": "有时候我只想赖在床上。"},
        {"word": "often", "phonetic": "/ˈɒfn/", "meaning": "adv. 经常", "example_en": "How often do you go to the gym?", "example_cn": "你多久去一次健身房？"},
        {"word": "usually", "phonetic": "/ˈjuːʒuəli/", "meaning": "adv. 通常", "example_en": "I usually drink coffee with my breakfast.", "example_cn": "我通常早餐时喝咖啡。"},
        {"word": "early", "phonetic": "/ˈɜːli/", "meaning": "adv. 早的", "example_en": "He arrived at the office very early.", "example_cn": "他很早就到了办公室。"},
        {"word": "late", "phonetic": "/leɪt/", "meaning": "adv. 晚的，迟的", "example_en": "Sorry I'm late, there was heavy traffic.", "example_cn": "抱歉我迟到了，路上很堵。"},
        {"word": "now", "phonetic": "/naʊ/", "meaning": "adv. 现在", "example_en": "We should leave right now.", "example_cn": "我们应该马上离开。"},
        {"word": "then", "phonetic": "/ðen/", "meaning": "adv. 那么；然后", "example_en": "Finish your dinner, then you can watch TV.", "example_cn": "吃完饭，然后你就可以看电视了。"},
        {"word": "before", "phonetic": "/bɪˈfɔː(r)/", "meaning": "prep. 在...之前", "example_en": "Wash your hands before you eat.", "example_cn": "吃饭前洗手。"},
        {"word": "after", "phonetic": "/ˈɑːftə(r)/", "meaning": "prep. 在...之后", "example_en": "Let's go for a walk after lunch.", "example_cn": "午饭后我们去散步吧。"},
        {"word": "time", "phonetic": "/taɪm/", "meaning": "n. 时间", "example_en": "What time does the movie start?", "example_cn": "电影几点开始？"}
    ],

    # -------------------------------------------------------------
    # Level 2: 海外生存 - 餐饮、出行与方向 - 50词
    # -------------------------------------------------------------
    2: [
        {"word": "receipt", "phonetic": "/rɪˈsiːt/", "meaning": "n. 收据", "example_en": "Do you need a receipt?", "example_cn": "你需要收据吗？"},
        {"word": "order", "phonetic": "/ˈɔːrdər/", "meaning": "v. 点餐", "example_en": "Are you ready to order?", "example_cn": "您准备好点餐了吗？"},
        {"word": "takeout", "phonetic": "/ˈteɪkaʊt/", "meaning": "n. 外卖", "example_en": "I'd like to get this for takeout.", "example_cn": "我想把这个打包带走。"},
        {"word": "cashier", "phonetic": "/kæˈʃɪr/", "meaning": "n. 收银员", "example_en": "Please pay the cashier.", "example_cn": "请去收银员那里付款。"},
        {"word": "discount", "phonetic": "/ˈdɪskaʊnt/", "meaning": "n. 折扣", "example_en": "Is there a discount for students?", "example_cn": "学生有打折吗？"},
        {"word": "menu", "phonetic": "/ˈmenjuː/", "meaning": "n. 菜单", "example_en": "Can I see the menu, please?", "example_cn": "能给我看看菜单吗？"},
        {"word": "bill", "phonetic": "/bɪl/", "meaning": "n. 账单", "example_en": "Could we have the bill, please?", "example_cn": "请买单。"},
        {"word": "tip", "phonetic": "/tɪp/", "meaning": "n. 小费", "example_en": "Don't forget to leave a tip.", "example_cn": "别忘了留小费。"},
        {"word": "napkin", "phonetic": "/ˈnæpkɪn/", "meaning": "n. 餐巾纸", "example_en": "Could I get some extra napkins?", "example_cn": "能多给我几张餐巾纸吗？"},
        {"word": "fork", "phonetic": "/fɔːrk/", "meaning": "n. 叉子", "example_en": "I dropped my fork.", "example_cn": "我的叉子掉了。"},
        {"word": "knife", "phonetic": "/naɪf/", "meaning": "n. 刀", "example_en": "I need a knife to cut the steak.", "example_cn": "我需要一把刀切牛排。"},
        {"word": "spoon", "phonetic": "/spuːn/", "meaning": "n. 勺子", "example_en": "Can I have a spoon for my soup?", "example_cn": "能给我把喝汤的勺子吗？"},
        {"word": "plate", "phonetic": "/pleɪt/", "meaning": "n. 盘子", "example_en": "Could we get an extra plate?", "example_cn": "能再给我们一个盘子吗？"},
        {"word": "delicious", "phonetic": "/dɪˈlɪʃəs/", "meaning": "adj. 美味的", "example_en": "The food here is delicious.", "example_cn": "这里的食物很美味。"},
        {"word": "spicy", "phonetic": "/ˈspaɪsi/", "meaning": "adj. 辣的", "example_en": "I love eating spicy food.", "example_cn": "我喜欢吃辣的食物。"},
        {"word": "sweet", "phonetic": "/swiːt/", "meaning": "adj. 甜的", "example_en": "This cake is too sweet.", "example_cn": "这块蛋糕太甜了。"},
        {"word": "sour", "phonetic": "/ˈsaʊər/", "meaning": "adj. 酸的", "example_en": "Lemons are very sour.", "example_cn": "柠檬非常酸。"},
        {"word": "bitter", "phonetic": "/ˈbɪtər/", "meaning": "adj. 苦的", "example_en": "Black coffee is bitter.", "example_cn": "黑咖啡很苦。"},
        {"word": "salty", "phonetic": "/ˈsɔːlti/", "meaning": "adj. 咸的", "example_en": "The soup is a bit salty.", "example_cn": "这汤有点咸。"},
        {"word": "vegetarian", "phonetic": "/ˌvedʒəˈteriən/", "meaning": "adj. 素食的", "example_en": "Do you have vegetarian options?", "example_cn": "你们有素食的选择吗？"},
        {"word": "allergy", "phonetic": "/ˈælərdʒi/", "meaning": "n. 过敏", "example_en": "I have an allergy to peanuts.", "example_cn": "我对花生过敏。"},
        {"word": "water", "phonetic": "/ˈwɔːtər/", "meaning": "n. 水", "example_en": "Can I get a glass of water?", "example_cn": "能给我一杯水吗？"},
        {"word": "ice", "phonetic": "/aɪs/", "meaning": "n. 冰", "example_en": "No ice, please.", "example_cn": "请去冰。"},
        {"word": "refill", "phonetic": "/ˈriːfɪl/", "meaning": "n. 续杯", "example_en": "Are refills free?", "example_cn": "续杯是免费的吗？"},
        {"word": "total", "phonetic": "/ˈtoʊtl/", "meaning": "n. 总计", "example_en": "What is the total cost?", "example_cn": "总费用是多少？"},
        {"word": "cash", "phonetic": "/kæʃ/", "meaning": "n. 现金", "example_en": "I will pay in cash.", "example_cn": "我会付现金。"},
        {"word": "credit", "phonetic": "/ˈkredɪt/", "meaning": "n. 信用卡", "example_en": "Do you take credit cards?", "example_cn": "你们收信用卡吗？"},
        {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "n. 零钱", "example_en": "Keep the change.", "example_cn": "不用找零了。"},
        {"word": "airport", "phonetic": "/ˈerpɔːrt/", "meaning": "n. 机场", "example_en": "How far is the airport?", "example_cn": "机场有多远？"},
        {"word": "flight", "phonetic": "/flaɪt/", "meaning": "n. 航班", "example_en": "My flight is delayed.", "example_cn": "我的航班延误了。"},
        {"word": "luggage", "phonetic": "/ˈlʌɡɪdʒ/", "meaning": "n. 行李", "example_en": "Where can I pick up my luggage?", "example_cn": "我在哪里拿行李？"},
        {"word": "passport", "phonetic": "/ˈpæspɔːrt/", "meaning": "n. 护照", "example_en": "Here is my passport.", "example_cn": "这是我的护照。"},
        {"word": "visa", "phonetic": "/ˈviːzə/", "meaning": "n. 签证", "example_en": "I need a student visa.", "example_cn": "我需要学生签证。"},
        {"word": "gate", "phonetic": "/ɡeɪt/", "meaning": "n. 登机口", "example_en": "Which gate is for flight 802?", "example_cn": "802航班在哪个登机口？"},
        {"word": "board", "phonetic": "/bɔːrd/", "meaning": "v. 登机", "example_en": "It is time to board the plane.", "example_cn": "该登机了。"},
        {"word": "delay", "phonetic": "/dɪˈleɪ/", "meaning": "n. 延误", "example_en": "The train has a short delay.", "example_cn": "火车有短暂的延误。"},
        {"word": "cancel", "phonetic": "/ˈkænsəl/", "meaning": "v. 取消", "example_en": "The meeting was canceled.", "example_cn": "会议被取消了。"},
        {"word": "arrive", "phonetic": "/əˈraɪv/", "meaning": "v. 到达", "example_en": "What time will we arrive?", "example_cn": "我们几点到达？"},
        {"word": "depart", "phonetic": "/dɪˈpɑːrt/", "meaning": "v. 出发", "example_en": "The bus departs at 9 AM.", "example_cn": "巴士早上9点出发。"},
        {"word": "taxi", "phonetic": "/ˈtæksi/", "meaning": "n. 出租车", "example_en": "Let's call a taxi.", "example_cn": "我们叫辆出租车吧。"},
        {"word": "subway", "phonetic": "/ˈsʌbweɪ/", "meaning": "n. 地铁", "example_en": "I take the subway to work.", "example_cn": "我坐地铁去上班。"},
        {"word": "station", "phonetic": "/ˈsteɪʃn/", "meaning": "n. 车站", "example_en": "Turn left at the train station.", "example_cn": "在火车站左转。"},
        {"word": "ticket", "phonetic": "/ˈtɪkɪt/", "meaning": "n. 票", "example_en": "Where can I buy a ticket?", "example_cn": "我在哪里可以买票？"},
        {"word": "map", "phonetic": "/mæp/", "meaning": "n. 地图", "example_en": "Can you show me on the map?", "example_cn": "你能在地图上指给我看吗？"},
        {"word": "street", "phonetic": "/striːt/", "meaning": "n. 街道", "example_en": "Go down this street.", "example_cn": "沿着这条街走。"},
        {"word": "corner", "phonetic": "/ˈkɔːrnər/", "meaning": "n. 拐角", "example_en": "The shop is on the corner.", "example_cn": "商店在街角。"},
        {"word": "straight", "phonetic": "/streɪt/", "meaning": "adv. 直走", "example_en": "Go straight ahead.", "example_cn": "一直往前走。"},
        {"word": "left", "phonetic": "/left/", "meaning": "adv. 左边", "example_en": "Turn left at the next light.", "example_cn": "在下一个红绿灯左转。"},
        {"word": "right", "phonetic": "/raɪt/", "meaning": "adv. 右边", "example_en": "It is on your right.", "example_cn": "它在你的右边。"},
        {"word": "crosswalk", "phonetic": "/ˈkrɔːswɔːk/", "meaning": "n. 人行横道", "example_en": "Always use the crosswalk.", "example_cn": "请务必走人行横道。"}
    ],

    # -------------------------------------------------------------
    # Level 3: 海外生存 - 购物、居住与求助 - 50词
    # -------------------------------------------------------------
    3: [
        {"word": "restroom", "phonetic": "/ˈrestrʊm/", "meaning": "n. 洗手间", "example_en": "Where is the restroom?", "example_cn": "请问洗手间在哪里？"},
        {"word": "pharmacy", "phonetic": "/ˈfɑːrməsi/", "meaning": "n. 药店", "example_en": "Is there a pharmacy nearby?", "example_cn": "附近有药店吗？"},
        {"word": "rent", "phonetic": "/rent/", "meaning": "n. 租金", "example_en": "How much is the rent?", "example_cn": "租金是多少？"},
        {"word": "appointment", "phonetic": "/əˈpɔɪntmənt/", "meaning": "n. 预约", "example_en": "I have a doctor's appointment.", "example_cn": "我有个看医生的预约。"},
        {"word": "emergency", "phonetic": "/ɪˈmɜːrdʒənsi/", "meaning": "n. 紧急情况", "example_en": "This is an emergency!", "example_cn": "这是紧急情况！"},
        {"word": "hospital", "phonetic": "/ˈhɑːspɪtl/", "meaning": "n. 医院", "example_en": "Take him to the hospital.", "example_cn": "送他去医院。"},
        {"word": "doctor", "phonetic": "/ˈdɑːktər/", "meaning": "n. 医生", "example_en": "I need to see a doctor.", "example_cn": "我需要看医生。"},
        {"word": "pain", "phonetic": "/peɪn/", "meaning": "n. 疼痛", "example_en": "I have pain in my chest.", "example_cn": "我胸口疼。"},
        {"word": "fever", "phonetic": "/ˈfiːvər/", "meaning": "n. 发烧", "example_en": "He has a high fever.", "example_cn": "他发高烧了。"},
        {"word": "cough", "phonetic": "/kɔːf/", "meaning": "v. 咳嗽", "example_en": "I have a bad cough.", "example_cn": "我咳得很厉害。"},
        {"word": "medicine", "phonetic": "/ˈmedɪsn/", "meaning": "n. 药", "example_en": "Take this medicine twice a day.", "example_cn": "这个药一天吃两次。"},
        {"word": "pill", "phonetic": "/pɪl/", "meaning": "n. 药丸", "example_en": "Swallow the pill with water.", "example_cn": "用水把药片吞下。"},
        {"word": "police", "phonetic": "/pəˈliːs/", "meaning": "n. 警察", "example_en": "Call the police!", "example_cn": "快报警！"},
        {"word": "help", "phonetic": "/help/", "meaning": "v. 帮助", "example_en": "Can you help me?", "example_cn": "你能帮帮我吗？"},
        {"word": "safe", "phonetic": "/seɪf/", "meaning": "adj. 安全的", "example_en": "Is it safe to walk here at night?", "example_cn": "晚上在这里走安全吗？"},
        {"word": "dangerous", "phonetic": "/ˈdeɪndʒərəs/", "meaning": "adj. 危险的", "example_en": "The road is very dangerous.", "example_cn": "这条路非常危险。"},
        {"word": "lost", "phonetic": "/lɔːst/", "meaning": "adj. 迷路的", "example_en": "I am lost. Can you help me?", "example_cn": "我迷路了。你能帮我吗？"},
        {"word": "found", "phonetic": "/faʊnd/", "meaning": "v. 找到", "example_en": "I found my keys.", "example_cn": "我找到我的钥匙了。"},
        {"word": "wallet", "phonetic": "/ˈwɑːlɪt/", "meaning": "n. 钱包", "example_en": "Someone stole my wallet.", "example_cn": "有人偷了我的钱包。"},
        {"word": "phone", "phonetic": "/foʊn/", "meaning": "n. 手机", "example_en": "My phone is out of service.", "example_cn": "我的手机没信号。"},
        {"word": "battery", "phonetic": "/ˈbætəri/", "meaning": "n. 电池", "example_en": "My phone battery is low.", "example_cn": "我手机快没电了。"},
        {"word": "charger", "phonetic": "/ˈtʃɑːrdʒər/", "meaning": "n. 充电器", "example_en": "Do you have a phone charger?", "example_cn": "你有手机充电器吗？"},
        {"word": "plug", "phonetic": "/plʌɡ/", "meaning": "n. 插头", "example_en": "Where is the plug?", "example_cn": "插头在哪里？"},
        {"word": "outlet", "phonetic": "/ˈaʊtlet/", "meaning": "n. 插座", "example_en": "Is there an outlet here?", "example_cn": "这里有电源插座吗？"},
        {"word": "store", "phonetic": "/stɔːr/", "meaning": "n. 商店", "example_en": "The store is closed today.", "example_cn": "商店今天关门。"},
        {"word": "open", "phonetic": "/ˈoʊpən/", "meaning": "adj. 营业的", "example_en": "Are you open on Sundays?", "example_cn": "你们星期天营业吗？"},
        {"word": "closed", "phonetic": "/kloʊzd/", "meaning": "adj. 关闭的", "example_en": "Sorry, we are closed.", "example_cn": "抱歉，我们关门了。"},
        {"word": "sale", "phonetic": "/seɪl/", "meaning": "n. 特卖", "example_en": "These shoes are on sale.", "example_cn": "这双鞋在打折。"},
        {"word": "price", "phonetic": "/praɪs/", "meaning": "n. 价格", "example_en": "What is the price of this?", "example_cn": "这个多少钱？"},
        {"word": "cheap", "phonetic": "/tʃiːp/", "meaning": "adj. 便宜的", "example_en": "It is very cheap.", "example_cn": "这个很便宜。"},
        {"word": "expensive", "phonetic": "/ɪkˈspensɪv/", "meaning": "adj. 贵的", "example_en": "That is too expensive for me.", "example_cn": "那个对我来说太贵了。"},
        {"word": "size", "phonetic": "/saɪz/", "meaning": "n. 尺寸", "example_en": "Do you have this in a larger size?", "example_cn": "你们有大一号的吗？"},
        {"word": "fit", "phonetic": "/fɪt/", "meaning": "v. 合身", "example_en": "This shirt doesn't fit me.", "example_cn": "这件衬衫我穿不合身。"},
        {"word": "try", "phonetic": "/traɪ/", "meaning": "v. 试穿", "example_en": "Can I try this on?", "example_cn": "我能试穿一下这个吗？"},
        {"word": "color", "phonetic": "/ˈkʌlər/", "meaning": "n. 颜色", "example_en": "Do you have this in a different color?", "example_cn": "这个有别的颜色吗？"},
        {"word": "refund", "phonetic": "/ˈriːfʌnd/", "meaning": "n. 退款", "example_en": "Can I get a refund?", "example_cn": "我能退款吗？"},
        {"word": "return", "phonetic": "/rɪˈtɜːrn/", "meaning": "v. 退货", "example_en": "I want to return this shirt.", "example_cn": "我想退掉这件衬衫。"},
        {"word": "exchange", "phonetic": "/ɪksˈtʃeɪndʒ/", "meaning": "v. 换货", "example_en": "Can I exchange it for a smaller one?", "example_cn": "我能换个小点的吗？"},
        {"word": "elevator", "phonetic": "/ˈelɪveɪtər/", "meaning": "n. 电梯", "example_en": "Take the elevator to the 3rd floor.", "example_cn": "坐电梯到三楼。"},
        {"word": "stairs", "phonetic": "/sterz/", "meaning": "n. 楼梯", "example_en": "The stairs are over there.", "example_cn": "楼梯在那边。"},
        {"word": "entrance", "phonetic": "/ˈentrəns/", "meaning": "n. 入口", "example_en": "Meet me at the main entrance.", "example_cn": "在正门入口见。"},
        {"word": "exit", "phonetic": "/ˈeɡzɪt/", "meaning": "n. 出口", "example_en": "Where is the emergency exit?", "example_cn": "紧急出口在哪里？"},
        {"word": "push", "phonetic": "/pʊʃ/", "meaning": "v. 推", "example_en": "Push the door open.", "example_cn": "把门推开。"},
        {"word": "pull", "phonetic": "/pʊl/", "meaning": "v. 拉", "example_en": "You need to pull to open it.", "example_cn": "你需要拉开它。"},
        {"word": "apartment", "phonetic": "/əˈpɑːrtmənt/", "meaning": "n. 公寓", "example_en": "I live in a small apartment.", "example_cn": "我住在一个小公寓里。"},
        {"word": "key", "phonetic": "/kiː/", "meaning": "n. 钥匙", "example_en": "I lost my room key.", "example_cn": "我把房间钥匙丢了。"},
        {"word": "lock", "phonetic": "/lɑːk/", "meaning": "v. 锁", "example_en": "Please lock the door when you leave.", "example_cn": "离开时请锁门。"},
        {"word": "neighbor", "phonetic": "/ˈneɪbər/", "meaning": "n. 邻居", "example_en": "My neighbor is very friendly.", "example_cn": "我的邻居很友好。"},
        {"word": "loud", "phonetic": "/laʊd/", "meaning": "adj. 吵闹的", "example_en": "The music is too loud.", "example_cn": "音乐太吵了。"},
        {"word": "quiet", "phonetic": "/ˈkwaɪət/", "meaning": "adj. 安静的", "example_en": "Please be quiet in the library.", "example_cn": "在图书馆请保持安静。"}
    ],

    # ==========================================
    # 🛒 Level 4: 海外生存 - 超市购物与居家饮食 (100词)
    # ==========================================
    4: [
        {"word": "fruit", "phonetic": "/fruːt/", "meaning": "n. 水果", "example_en": "Eat more fruit.", "example_cn": "多吃水果。"},
        {"word": "apple", "phonetic": "/ˈæpəl/", "meaning": "n. 苹果", "example_en": "I want an apple.", "example_cn": "我想要一个苹果。"},
        {"word": "banana", "phonetic": "/bəˈnænə/", "meaning": "n. 香蕉", "example_en": "The banana is sweet.", "example_cn": "这香蕉很甜。"},
        {"word": "orange", "phonetic": "/ˈɔːrɪndʒ/", "meaning": "n. 橙子", "example_en": "I need some oranges.", "example_cn": "我需要一些橙子。"},
        {"word": "grape", "phonetic": "/ɡreɪp/", "meaning": "n. 葡萄", "example_en": "These grapes are fresh.", "example_cn": "这些葡萄很新鲜。"},
        {"word": "strawberry", "phonetic": "/ˈstrɔːberi/", "meaning": "n. 草莓", "example_en": "She loves strawberries.", "example_cn": "她喜欢草莓。"},
        {"word": "watermelon", "phonetic": "/ˈwɔːtərmelən/", "meaning": "n. 西瓜", "example_en": "Buy a big watermelon.", "example_cn": "买个大西瓜。"},
        {"word": "lemon", "phonetic": "/ˈlemən/", "meaning": "n. 柠檬", "example_en": "I need a lemon.", "example_cn": "我需要一个柠檬。"},
        {"word": "peach", "phonetic": "/piːtʃ/", "meaning": "n. 桃子", "example_en": "This peach is soft.", "example_cn": "这个桃子很软。"},
        {"word": "pear", "phonetic": "/per/", "meaning": "n. 梨", "example_en": "Have a pear.", "example_cn": "吃个梨吧。"},
        {"word": "tomato", "phonetic": "/təˈmeɪtoʊ/", "meaning": "n. 西红柿", "example_en": "Cut the tomato.", "example_cn": "把西红柿切开。"},
        {"word": "potato", "phonetic": "/təˈpeɪtoʊ/", "meaning": "n. 土豆", "example_en": "I like baked potatoes.", "example_cn": "我喜欢烤土豆。"},
        {"word": "onion", "phonetic": "/ˈʌnjən/", "meaning": "n. 洋葱", "example_en": "Chop the onion.", "example_cn": "把洋葱切碎。"},
        {"word": "garlic", "phonetic": "/ˈɡɑːrlɪk/", "meaning": "n. 大蒜", "example_en": "Add some garlic.", "example_cn": "加点大蒜。"},
        {"word": "carrot", "phonetic": "/ˈkærət/", "meaning": "n. 胡萝卜", "example_en": "Rabbits eat carrots.", "example_cn": "兔子吃胡萝卜。"},
        {"word": "mushroom", "phonetic": "/ˈmʌʃrʊm/", "meaning": "n. 蘑菇", "example_en": "I want mushroom soup.", "example_cn": "我想要蘑菇汤。"},
        {"word": "cabbage", "phonetic": "/ˈkæbɪdʒ/", "meaning": "n. 卷心菜", "example_en": "Wash the cabbage.", "example_cn": "洗一下卷心菜。"},
        {"word": "fish", "phonetic": "/fɪʃ/", "meaning": "n. 鱼", "example_en": "I don't eat fish.", "example_cn": "我不吃鱼。"},
        {"word": "shrimp", "phonetic": "/ʃrɪmp/", "meaning": "n. 虾", "example_en": "Fried shrimp is good.", "example_cn": "炸虾很好吃。"},
        {"word": "egg", "phonetic": "/eɡ/", "meaning": "n. 鸡蛋", "example_en": "Boil an egg.", "example_cn": "煮个鸡蛋。"},
        {"word": "milk", "phonetic": "/mɪlk/", "meaning": "n. 牛奶", "example_en": "Drink your milk.", "example_cn": "把牛奶喝了。"},
        {"word": "yogurt", "phonetic": "/ˈjoʊɡərt/", "meaning": "n. 酸奶", "example_en": "I have yogurt for breakfast.", "example_cn": "我早餐吃酸奶。"},
        {"word": "bread", "phonetic": "/bred/", "meaning": "n. 面包", "example_en": "Buy some bread.", "example_cn": "买点面包。"},
        {"word": "cake", "phonetic": "/keɪk/", "meaning": "n. 蛋糕", "example_en": "It is a birthday cake.", "example_cn": "这是一个生日蛋糕。"},
        {"word": "cookie", "phonetic": "/ˈkʊki/", "meaning": "n. 饼干", "example_en": "Have a chocolate cookie.", "example_cn": "吃块巧克力饼干吧。"},
        {"word": "candy", "phonetic": "/ˈkændi/", "meaning": "n. 糖果", "example_en": "Kids love candy.", "example_cn": "小孩喜欢糖果。"},
        {"word": "chocolate", "phonetic": "/ˈtʃɔːklət/", "meaning": "n. 巧克力", "example_en": "This chocolate is dark.", "example_cn": "这是黑巧克力。"},
        {"word": "rice", "phonetic": "/raɪs/", "meaning": "n. 米饭", "example_en": "We eat rice every day.", "example_cn": "我们每天吃米饭。"},
        {"word": "noodle", "phonetic": "/ˈnuːdl/", "meaning": "n. 面条", "example_en": "I ordered beef noodles.", "example_cn": "我点了牛肉面。"},
        {"word": "pasta", "phonetic": "/ˈpɑːstə/", "meaning": "n. 意面", "example_en": "Cook the pasta.", "example_cn": "煮意大利面。"},
        {"word": "breakfast", "phonetic": "/ˈbrekfəst/", "meaning": "n. 早餐", "example_en": "Breakfast is ready.", "example_cn": "早餐准备好了。"},
        {"word": "lunch", "phonetic": "/lʌntʃ/", "meaning": "n. 午餐", "example_en": "Let's have lunch.", "example_cn": "我们吃午饭吧。"},
        {"word": "dinner", "phonetic": "/ˈdɪnər/", "meaning": "n. 晚餐", "example_en": "What is for dinner?", "example_cn": "晚饭吃什么？"},
        {"word": "snack", "phonetic": "/snæk/", "meaning": "n. 零食", "example_en": "I need a snack.", "example_cn": "我需要吃点零食。"},
        {"word": "drink", "phonetic": "/drɪŋk/", "meaning": "v. 喝", "example_en": "What do you want to drink?", "example_cn": "你想喝点什么？"},
        {"word": "coffee", "phonetic": "/ˈkɔːfi/", "meaning": "n. 咖啡", "example_en": "A cup of coffee, please.", "example_cn": "请给我一杯咖啡。"},
        {"word": "tea", "phonetic": "/tiː/", "meaning": "n. 茶", "example_en": "I prefer green tea.", "example_cn": "我更喜欢绿茶。"},
        {"word": "beer", "phonetic": "/bɪr/", "meaning": "n. 啤酒", "example_en": "Two beers, please.", "example_cn": "请来两杯啤酒。"},
        {"word": "wine", "phonetic": "/waɪn/", "meaning": "n. 葡萄酒", "example_en": "A glass of red wine.", "example_cn": "一杯红酒。"},
        {"word": "cup", "phonetic": "/kʌp/", "meaning": "n. 杯子", "example_en": "The cup is empty.", "example_cn": "杯子是空的。"},
        {"word": "glass", "phonetic": "/ɡlæs/", "meaning": "n. 玻璃杯", "example_en": "A glass of water.", "example_cn": "一杯水。"},
        {"word": "bowl", "phonetic": "/boʊl/", "meaning": "n. 碗", "example_en": "A bowl of rice.", "example_cn": "一碗米饭。"},
        {"word": "chopstick", "phonetic": "/ˈtʃɑːpstɪk/", "meaning": "n. 筷子", "example_en": "Can you use chopsticks?", "example_cn": "你会用筷子吗？"},
        {"word": "pot", "phonetic": "/pɑːt/", "meaning": "n. 锅", "example_en": "The pot is hot.", "example_cn": "锅很烫。"},
        {"word": "pan", "phonetic": "/pæn/", "meaning": "n. 平底锅", "example_en": "Fry it in the pan.", "example_cn": "在平底锅里煎一下。"},
        {"word": "stove", "phonetic": "/stoʊv/", "meaning": "n. 炉子", "example_en": "Turn off the stove.", "example_cn": "关掉炉子。"},
        {"word": "oven", "phonetic": "/ˈʌvn/", "meaning": "n. 烤箱", "example_en": "Put it in the oven.", "example_cn": "把它放进烤箱。"},
        {"word": "fridge", "phonetic": "/frɪdʒ/", "meaning": "n. 冰箱", "example_en": "Keep it in the fridge.", "example_cn": "把它保存在冰箱里。"},
        {"word": "microwave", "phonetic": "/ˈmaɪkrəweɪv/", "meaning": "n. 微波炉", "example_en": "Use the microwave to heat it.", "example_cn": "用微波炉加热一下。"},
        {"word": "wash", "phonetic": "/wɑːʃ/", "meaning": "v. 洗", "example_en": "Wash your hands.", "example_cn": "洗洗手。"},
        {"word": "wipe", "phonetic": "/waɪp/", "meaning": "v. 擦", "example_en": "Wipe the table.", "example_cn": "擦一下桌子。"},
        {"word": "sweep", "phonetic": "/swiːp/", "meaning": "v. 扫", "example_en": "Sweep the floor.", "example_cn": "扫一下地。"},
        {"word": "trash", "phonetic": "/træʃ/", "meaning": "n. 垃圾", "example_en": "Take out the trash.", "example_cn": "去倒垃圾。"},
        {"word": "garbage", "phonetic": "/ˈɡɑːrbɪdʒ/", "meaning": "n. 垃圾", "example_en": "Where is the garbage can?", "example_cn": "垃圾桶在哪里？"},
        {"word": "bag", "phonetic": "/bæɡ/", "meaning": "n. 袋子", "example_en": "I need a plastic bag.", "example_cn": "我需要一个塑料袋。"},
        {"word": "box", "phonetic": "/bɑːks/", "meaning": "n. 盒子，箱子", "example_en": "Open the box.", "example_cn": "打开箱子。"},
        {"word": "bottle", "phonetic": "/ˈbɑːtl/", "meaning": "n. 瓶子", "example_en": "A bottle of water.", "example_cn": "一瓶水。"},
        {"word": "can", "phonetic": "/kæn/", "meaning": "n. 易拉罐", "example_en": "A can of soda.", "example_cn": "一罐汽水。"},
        {"word": "cut", "phonetic": "/kʌt/", "meaning": "v. 切", "example_en": "Cut the apple.", "example_cn": "把苹果切开。"},
        {"word": "boil", "phonetic": "/bɔɪl/", "meaning": "v. 煮沸", "example_en": "Boil some water.", "example_cn": "烧点水。"},
        {"word": "fry", "phonetic": "/fraɪ/", "meaning": "v. 煎", "example_en": "Fry the egg.", "example_cn": "煎个蛋。"},
        {"word": "bake", "phonetic": "/beɪk/", "meaning": "v. 烤", "example_en": "Bake a cake.", "example_cn": "烤个蛋糕。"},
        {"word": "pour", "phonetic": "/pɔːr/", "meaning": "v. 倒", "example_en": "Pour me some tea.", "example_cn": "给我倒点茶。"},
        {"word": "mix", "phonetic": "/mɪks/", "meaning": "v. 混合", "example_en": "Mix them together.", "example_cn": "把它们混在一起。"},
        {"word": "stir", "phonetic": "/stɜːr/", "meaning": "v. 搅拌", "example_en": "Stir the soup.", "example_cn": "搅拌一下汤。"},
        {"word": "taste", "phonetic": "/teɪst/", "meaning": "v. 品尝", "example_en": "Taste this.", "example_cn": "尝尝这个。"},
        {"word": "hot", "phonetic": "/hɑːt/", "meaning": "adj. 烫的", "example_en": "The coffee is too hot.", "example_cn": "咖啡太烫了。"},
        {"word": "cold", "phonetic": "/koʊld/", "meaning": "adj. 冷的", "example_en": "I want a cold drink.", "example_cn": "我想要一杯冷饮。"},
        {"word": "warm", "phonetic": "/wɔːrm/", "meaning": "adj. 温暖的", "example_en": "Keep warm.", "example_cn": "注意保暖。"},
        {"word": "rotten", "phonetic": "/ˈrɑːtn/", "meaning": "adj. 腐烂的", "example_en": "The apple is rotten.", "example_cn": "这个苹果烂了。"},
        {"word": "full", "phonetic": "/fʊl/", "meaning": "adj. 满的", "example_en": "I am full.", "example_cn": "我吃饱了。"},
        {"word": "empty", "phonetic": "/ˈempti/", "meaning": "adj. 空的", "example_en": "The box is empty.", "example_cn": "盒子是空的。"},
        {"word": "heavy", "phonetic": "/ˈhevi/", "meaning": "adj. 重的", "example_en": "This bag is heavy.", "example_cn": "这个包很重。"},
        {"word": "light", "phonetic": "/laɪt/", "meaning": "adj. 轻的", "example_en": "It is very light.", "example_cn": "它非常轻。"},
        {"word": "basket", "phonetic": "/ˈbæskɪt/", "meaning": "n. 篮子", "example_en": "Take a shopping basket.", "example_cn": "拿一个购物篮。"},
        {"word": "shelf", "phonetic": "/ʃelf/", "meaning": "n. 货架", "example_en": "It is on the top shelf.", "example_cn": "它在最上面的架子上。"},
        {"word": "aisle", "phonetic": "/aɪl/", "meaning": "n. 过道", "example_en": "Go to aisle 5.", "example_cn": "去5号过道。"},
        {"word": "frozen", "phonetic": "/ˈfroʊzn/", "meaning": "adj. 冷冻的", "example_en": "Where is the frozen food?", "example_cn": "冷冻食品在哪？"},
        {"word": "produce", "phonetic": "/ˈprɑːduːs/", "meaning": "n. 农产品", "example_en": "I am in the produce section.", "example_cn": "我在农产品区。"},
        {"word": "bakery", "phonetic": "/ˈbeɪkəri/", "meaning": "n. 面包店", "example_en": "The bakery smells good.", "example_cn": "面包店闻起来很香。"},
        {"word": "dairy", "phonetic": "/ˈderi/", "meaning": "n. 乳制品", "example_en": "Milk is a dairy product.", "example_cn": "牛奶是乳制品。"},
        {"word": "scale", "phonetic": "/skeɪl/", "meaning": "n. 秤", "example_en": "Put it on the scale.", "example_cn": "把它放在秤上。"},
        {"word": "plastic", "phonetic": "/ˈplæstɪk/", "meaning": "n. 塑料", "example_en": "No plastic bags, please.", "example_cn": "请不要用塑料袋。"},
        {"word": "counter", "phonetic": "/ˈkaʊntər/", "meaning": "n. 柜台", "example_en": "Pay at the counter.", "example_cn": "在柜台付款。"},
        {"word": "buy", "phonetic": "/baɪ/", "meaning": "v. 买", "example_en": "I want to buy this.", "example_cn": "我想买这个。"},
        {"word": "sell", "phonetic": "/sel/", "meaning": "v. 卖", "example_en": "Do you sell stamps?", "example_cn": "你们卖邮票吗？"},
        {"word": "pay", "phonetic": "/peɪ/", "meaning": "v. 支付", "example_en": "How would you like to pay?", "example_cn": "您想怎么付款？"},
        {"word": "cost", "phonetic": "/kɔːst/", "meaning": "v. 花费", "example_en": "How much does it cost?", "example_cn": "这个多少钱？"},
        {"word": "money", "phonetic": "/ˈmʌni/", "meaning": "n. 钱", "example_en": "I don't have enough money.", "example_cn": "我钱不够。"},
        {"word": "coin", "phonetic": "/kɔɪn/", "meaning": "n. 硬币", "example_en": "Do you have any coins?", "example_cn": "你有硬币吗？"},
        {"word": "shampoo", "phonetic": "/ʃæmˈpuː/", "meaning": "n. 洗发水", "example_en": "I need to buy shampoo.", "example_cn": "我需要买洗发水。"},
        {"word": "toothpaste", "phonetic": "/ˈtuːθpeɪst/", "meaning": "n. 牙膏", "example_en": "We are out of toothpaste.", "example_cn": "我们牙膏用完了。"},
        {"word": "toothbrush", "phonetic": "/ˈtuːθbrʌʃ/", "meaning": "n. 牙刷", "example_en": "I bought a new toothbrush.", "example_cn": "我买了一把新牙刷。"},
        {"word": "tissue", "phonetic": "/ˈtɪʃuː/", "meaning": "n. 纸巾", "example_en": "Can I have a tissue?", "example_cn": "能给我一张纸巾吗？"},
        {"word": "paper", "phonetic": "/ˈpeɪpər/", "meaning": "n. 纸", "example_en": "I need some paper.", "example_cn": "我需要一些纸。"},
        {"word": "scissors", "phonetic": "/ˈsɪzərz/", "meaning": "n. 剪刀", "example_en": "Where are the scissors?", "example_cn": "剪刀在哪？"},
        {"word": "umbrella", "phonetic": "/ʌmˈbrelə/", "meaning": "n. 雨伞", "example_en": "Take an umbrella.", "example_cn": "带上雨伞。"},
        {"word": "purse", "phonetic": "/pɜːrs/", "meaning": "n. 女用钱包", "example_en": "My phone is in my purse.", "example_cn": "手机在我的包里。"},
        {"word": "glasses", "phonetic": "/ˈɡlæsɪz/", "meaning": "n. 眼镜", "example_en": "I can't find my glasses.", "example_cn": "我找不到我的眼镜了。"},
        {"word": "watch", "phonetic": "/wɑːtʃ/", "meaning": "n. 手表", "example_en": "What a nice watch!", "example_cn": "多好看的手表！"}
    ],

    # ==========================================
    # 👕 Level 5: 海外生存 - 身体、衣物与家庭关系 (100词)
    # ==========================================
    5: [
        {"word": "body", "phonetic": "/ˈbɑːdi/", "meaning": "n. 身体", "example_en": "Listen to your body.", "example_cn": "倾听你身体的声音。"},
        {"word": "head", "phonetic": "/hed/", "meaning": "n. 头", "example_en": "My head hurts.", "example_cn": "我头疼。"},
        {"word": "face", "phonetic": "/feɪs/", "meaning": "n. 脸", "example_en": "Wash your face.", "example_cn": "洗洗脸。"},
        {"word": "eye", "phonetic": "/aɪ/", "meaning": "n. 眼睛", "example_en": "Close your eyes.", "example_cn": "闭上眼睛。"},
        {"word": "ear", "phonetic": "/ɪr/", "meaning": "n. 耳朵", "example_en": "My right ear hurts.", "example_cn": "我右耳疼。"},
        {"word": "nose", "phonetic": "/noʊz/", "meaning": "n. 鼻子", "example_en": "Touch your nose.", "example_cn": "摸摸你的鼻子。"},
        {"word": "mouth", "phonetic": "/maʊθ/", "meaning": "n. 嘴", "example_en": "Open your mouth.", "example_cn": "张开嘴。"},
        {"word": "tooth", "phonetic": "/tuːθ/", "meaning": "n. 牙齿", "example_en": "I have a bad tooth.", "example_cn": "我有一颗坏牙。"},
        {"word": "hair", "phonetic": "/her/", "meaning": "n. 头发", "example_en": "Brush your hair.", "example_cn": "梳梳头发。"},
        {"word": "hand", "phonetic": "/hænd/", "meaning": "n. 手", "example_en": "Give me your hand.", "example_cn": "把手给我。"},
        {"word": "arm", "phonetic": "/ɑːrm/", "meaning": "n. 手臂", "example_en": "My arm is broken.", "example_cn": "我手臂骨折了。"},
        {"word": "leg", "phonetic": "/leɡ/", "meaning": "n. 腿", "example_en": "My legs are tired.", "example_cn": "我腿酸了。"},
        {"word": "foot", "phonetic": "/fʊt/", "meaning": "n. 脚", "example_en": "My left foot hurts.", "example_cn": "我左脚疼。"},
        {"word": "heart", "phonetic": "/hɑːrt/", "meaning": "n. 心脏", "example_en": "My heart beats fast.", "example_cn": "我心跳得很快。"},
        {"word": "stomach", "phonetic": "/ˈstʌmək/", "meaning": "n. 肚子", "example_en": "My stomach hurts.", "example_cn": "我肚子疼。"},
        {"word": "back", "phonetic": "/bæk/", "meaning": "n. 背部", "example_en": "My back aches.", "example_cn": "我背痛。"},
        {"word": "neck", "phonetic": "/nek/", "meaning": "n. 脖子", "example_en": "I have a stiff neck.", "example_cn": "我脖子僵硬。"},
        {"word": "shoulder", "phonetic": "/ˈʃoʊldər/", "meaning": "n. 肩膀", "example_en": "Relax your shoulders.", "example_cn": "放松你的肩膀。"},
        {"word": "finger", "phonetic": "/ˈfɪŋɡər/", "meaning": "n. 手指", "example_en": "I cut my finger.", "example_cn": "我切到手指了。"},
        {"word": "toe", "phonetic": "/toʊ/", "meaning": "n. 脚趾", "example_en": "I stubbed my toe.", "example_cn": "我踢到了脚趾。"},
        {"word": "skin", "phonetic": "/skɪn/", "meaning": "n. 皮肤", "example_en": "My skin is dry.", "example_cn": "我皮肤很干。"},
        {"word": "bone", "phonetic": "/boʊn/", "meaning": "n. 骨头", "example_en": "He broke a bone.", "example_cn": "他摔断了一根骨头。"},
        {"word": "blood", "phonetic": "/blʌd/", "meaning": "n. 血液", "example_en": "I see blood.", "example_cn": "我看到血了。"},
        {"word": "healthy", "phonetic": "/ˈhelθi/", "meaning": "adj. 健康的", "example_en": "Stay healthy.", "example_cn": "保持健康。"},
        {"word": "weak", "phonetic": "/wiːk/", "meaning": "adj. 虚弱的", "example_en": "I feel weak.", "example_cn": "我觉得很虚弱。"},
        {"word": "strong", "phonetic": "/strɔːŋ/", "meaning": "adj. 强壮的", "example_en": "He is very strong.", "example_cn": "他很强壮。"},
        {"word": "hurt", "phonetic": "/hɜːrt/", "meaning": "v. 受伤", "example_en": "Does it hurt?", "example_cn": "这里疼吗？"},
        {"word": "bleed", "phonetic": "/bliːd/", "meaning": "v. 流血", "example_en": "My nose is bleeding.", "example_cn": "我流鼻血了。"},
        {"word": "cure", "phonetic": "/kjʊr/", "meaning": "v. 治愈", "example_en": "There is no cure.", "example_cn": "没有治愈的方法。"},
        {"word": "heal", "phonetic": "/hiːl/", "meaning": "v. 愈合", "example_en": "The wound will heal.", "example_cn": "伤口会愈合的。"},
        {"word": "clothes", "phonetic": "/kloʊðz/", "meaning": "n. 衣服", "example_en": "Put on your clothes.", "example_cn": "穿上衣服。"},
        {"word": "shirt", "phonetic": "/ʃɜːrt/", "meaning": "n. 衬衫", "example_en": "I like this shirt.", "example_cn": "我喜欢这件衬衫。"},
        {"word": "t-shirt", "phonetic": "/ˈtiː ʃɜːrt/", "meaning": "n. T恤", "example_en": "He wears a T-shirt.", "example_cn": "他穿着一件T恤。"},
        {"word": "pants", "phonetic": "/pænts/", "meaning": "n. 裤子", "example_en": "These pants are too long.", "example_cn": "这条裤子太长了。"},
        {"word": "jeans", "phonetic": "/dʒiːnz/", "meaning": "n. 牛仔裤", "example_en": "I bought new jeans.", "example_cn": "我买了新牛仔裤。"},
        {"word": "dress", "phonetic": "/dres/", "meaning": "n. 连衣裙", "example_en": "What a beautiful dress!", "example_cn": "多漂亮的裙子！"},
        {"word": "skirt", "phonetic": "/skɜːrt/", "meaning": "n. 短裙", "example_en": "She wears a skirt.", "example_cn": "她穿着短裙。"},
        {"word": "sweater", "phonetic": "/ˈswetər/", "meaning": "n. 毛衣", "example_en": "Put on a sweater.", "example_cn": "穿上毛衣吧。"},
        {"word": "jacket", "phonetic": "/ˈdʒækɪt/", "meaning": "n. 夹克", "example_en": "I need a jacket.", "example_cn": "我需要一件夹克。"},
        {"word": "coat", "phonetic": "/koʊt/", "meaning": "n. 外套", "example_en": "Take your coat.", "example_cn": "带上你的外套。"},
        {"word": "shoe", "phonetic": "/ʃuː/", "meaning": "n. 鞋子", "example_en": "Take off your shoes.", "example_cn": "脱掉你的鞋子。"},
        {"word": "sock", "phonetic": "/sɑːk/", "meaning": "n. 袜子", "example_en": "I need clean socks.", "example_cn": "我需要干净的袜子。"},
        {"word": "hat", "phonetic": "/hæt/", "meaning": "n. 帽子", "example_en": "Wear a hat.", "example_cn": "戴顶帽子。"},
        {"word": "glove", "phonetic": "/ɡlʌv/", "meaning": "n. 手套", "example_en": "Where are my gloves?", "example_cn": "我的手套在哪？"},
        {"word": "scarf", "phonetic": "/skɑːrf/", "meaning": "n. 围巾", "example_en": "Wrap a scarf around your neck.", "example_cn": "在脖子上围条围巾。"},
        {"word": "belt", "phonetic": "/belt/", "meaning": "n. 皮带", "example_en": "I need a belt.", "example_cn": "我需要一条皮带。"},
        {"word": "uniform", "phonetic": "/ˈjuːnɪfɔːrm/", "meaning": "n. 制服", "example_en": "He is in uniform.", "example_cn": "他穿着制服。"},
        {"word": "suit", "phonetic": "/suːt/", "meaning": "n. 西装", "example_en": "He wore a black suit.", "example_cn": "他穿了一套黑西装。"},
        {"word": "tie", "phonetic": "/taɪ/", "meaning": "n. 领带", "example_en": "He is wearing a tie.", "example_cn": "他戴着领带。"},
        {"word": "wear", "phonetic": "/wer/", "meaning": "v. 穿", "example_en": "What should I wear?", "example_cn": "我该穿什么？"},
        {"word": "dry", "phonetic": "/draɪ/", "meaning": "v. 擦干", "example_en": "Dry your hands.", "example_cn": "把手擦干。"},
        {"word": "fold", "phonetic": "/foʊld/", "meaning": "v. 折叠", "example_en": "Fold the clothes.", "example_cn": "把衣服叠好。"},
        {"word": "iron", "phonetic": "/ˈaɪərn/", "meaning": "v. 熨烫", "example_en": "I need to iron my shirt.", "example_cn": "我需要熨一下衬衫。"},
        {"word": "family", "phonetic": "/ˈfæməli/", "meaning": "n. 家人", "example_en": "I love my family.", "example_cn": "我爱我的家人。"},
        {"word": "father", "phonetic": "/ˈfɑːðər/", "meaning": "n. 父亲", "example_en": "He is my father.", "example_cn": "他是我的父亲。"},
        {"word": "mother", "phonetic": "/ˈmʌðər/", "meaning": "n. 母亲", "example_en": "She is my mother.", "example_cn": "她是我母亲。"},
        {"word": "son", "phonetic": "/sʌn/", "meaning": "n. 儿子", "example_en": "They have one son.", "example_cn": "他们有一个儿子。"},
        {"word": "daughter", "phonetic": "/ˈdɔːtər/", "meaning": "n. 女儿", "example_en": "She is my daughter.", "example_cn": "她是我的女儿。"},
        {"word": "brother", "phonetic": "/ˈbrʌðər/", "meaning": "n. 兄弟", "example_en": "He is my brother.", "example_cn": "他是我的兄弟。"},
        {"word": "sister", "phonetic": "/ˈsɪstər/", "meaning": "n. 姐妹", "example_en": "I have a sister.", "example_cn": "我有一个妹妹。"},
        {"word": "husband", "phonetic": "/ˈhʌzbənd/", "meaning": "n. 丈夫", "example_en": "This is my husband.", "example_cn": "这是我的丈夫。"},
        {"word": "wife", "phonetic": "/waɪf/", "meaning": "n. 妻子", "example_en": "Meet my wife.", "example_cn": "见见我的妻子。"},
        {"word": "friend", "phonetic": "/frend/", "meaning": "n. 朋友", "example_en": "He is my best friend.", "example_cn": "他是我最好的朋友。"},
        {"word": "colleague", "phonetic": "/ˈkɑːliːɡ/", "meaning": "n. 同事", "example_en": "She is my colleague.", "example_cn": "她是我的同事。"},
        {"word": "meet", "phonetic": "/miːt/", "meaning": "v. 遇见", "example_en": "Nice to meet you.", "example_cn": "很高兴认识你。"},
        {"word": "talk", "phonetic": "/tɔːk/", "meaning": "v. 谈话", "example_en": "Can we talk?", "example_cn": "我们能谈谈吗？"},
        {"word": "speak", "phonetic": "/spiːk/", "meaning": "v. 说话", "example_en": "Do you speak English?", "example_cn": "你说英语吗？"},
        {"word": "say", "phonetic": "/seɪ/", "meaning": "v. 说", "example_en": "What did you say?", "example_cn": "你说了什么？"},
        {"word": "tell", "phonetic": "/tel/", "meaning": "v. 告诉", "example_en": "Tell me the truth.", "example_cn": "告诉我真相。"},
        {"word": "ask", "phonetic": "/æsk/", "meaning": "v. 问", "example_en": "Can I ask a question?", "example_cn": "我能问个问题吗？"},
        {"word": "answer", "phonetic": "/ˈænsər/", "meaning": "v. 回答", "example_en": "Answer the phone.", "example_cn": "接电话。"},
        {"word": "listen", "phonetic": "/ˈlɪsn/", "meaning": "v. 听", "example_en": "Listen to me.", "example_cn": "听我说。"},
        {"word": "hear", "phonetic": "/hɪr/", "meaning": "v. 听见", "example_en": "I can't hear you.", "example_cn": "我听不见你说话。"},
        {"word": "see", "phonetic": "/siː/", "meaning": "v. 看见", "example_en": "Let me see.", "example_cn": "让我看看。"},
        {"word": "watch", "phonetic": "/wɑːtʃ/", "meaning": "v. 观看", "example_en": "Watch this.", "example_cn": "看这个。"},
        {"word": "look", "phonetic": "/lʊk/", "meaning": "v. 看", "example_en": "Look at here.", "example_cn": "看这里。"},
        {"word": "smile", "phonetic": "/smaɪl/", "meaning": "v. 微笑", "example_en": "Just smile.", "example_cn": "微笑就好。"},
        {"word": "laugh", "phonetic": "/læf/", "meaning": "v. 大笑", "example_en": "Don't laugh at me.", "example_cn": "别笑我。"},
        {"word": "cry", "phonetic": "/kraɪ/", "meaning": "v. 哭泣", "example_en": "Please don't cry.", "example_cn": "请别哭。"},
        {"word": "hug", "phonetic": "/hʌɡ/", "meaning": "v. 拥抱", "example_en": "Give me a hug.", "example_cn": "给我一个拥抱。"},
        {"word": "kiss", "phonetic": "/kɪs/", "meaning": "v. 吻", "example_en": "Kiss me goodbye.", "example_cn": "吻别。"},
        {"word": "love", "phonetic": "/lʌv/", "meaning": "v. 爱", "example_en": "I love you.", "example_cn": "我爱你。"},
        {"word": "hate", "phonetic": "/heɪt/", "meaning": "v. 讨厌", "example_en": "I hate waiting.", "example_cn": "我讨厌等待。"},
        {"word": "like", "phonetic": "/laɪk/", "meaning": "v. 喜欢", "example_en": "Do you like it?", "example_cn": "你喜欢它吗？"},
        {"word": "dislike", "phonetic": "/dɪsˈlaɪk/", "meaning": "v. 不喜欢", "example_en": "I dislike the cold.", "example_cn": "我不喜欢寒冷。"},
        {"word": "care", "phonetic": "/ker/", "meaning": "v. 在乎", "example_en": "I don't care.", "example_cn": "我不在乎。"},
        {"word": "worry", "phonetic": "/ˈwɜːri/", "meaning": "v. 担心", "example_en": "Don't worry.", "example_cn": "别担心。"},
        {"word": "miss", "phonetic": "/mɪs/", "meaning": "v. 想念", "example_en": "I miss my home.", "example_cn": "我想家了。"},
        {"word": "remember", "phonetic": "/rɪˈmembər/", "meaning": "v. 记得", "example_en": "Do you remember me?", "example_cn": "你记得我吗？"},
        {"word": "forget", "phonetic": "/fərˈɡet/", "meaning": "v. 忘记", "example_en": "Don't forget your bag.", "example_cn": "别忘了你的包。"},
        {"word": "think", "phonetic": "/θɪŋk/", "meaning": "v. 思考", "example_en": "Let me think.", "example_cn": "让我想想。"},
        {"word": "know", "phonetic": "/noʊ/", "meaning": "v. 知道", "example_en": "I don't know.", "example_cn": "我不知道。"},
        {"word": "understand", "phonetic": "/ˌʌndərˈstænd/", "meaning": "v. 明白", "example_en": "I understand now.", "example_cn": "我现在明白了。"},
        {"word": "believe", "phonetic": "/bɪˈliːv/", "meaning": "v. 相信", "example_en": "Believe me.", "example_cn": "相信我。"},
        {"word": "hope", "phonetic": "/hoʊp/", "meaning": "v. 希望", "example_en": "I hope so.", "example_cn": "希望如此。"},
        {"word": "wish", "phonetic": "/wɪʃ/", "meaning": "v. 祝愿", "example_en": "Make a wish.", "example_cn": "许个愿吧。"},
        {"word": "guess", "phonetic": "/ɡes/", "meaning": "v. 猜", "example_en": "Guess what?", "example_cn": "猜怎么着？"},
        {"word": "mean", "phonetic": "/miːn/", "meaning": "v. 意思是", "example_en": "What do you mean?", "example_cn": "你什么意思？"},
        {"word": "decide", "phonetic": "/dɪˈsaɪd/", "meaning": "v. 决定", "example_en": "You decide.", "example_cn": "你来决定。"}
    ],

    # ==========================================
    # 🏙️ Level 6: 海外生存 - 城市认路、天气与万能形容词 (100词)
    # ==========================================
    6: [
        {"word": "city", "phonetic": "/ˈsɪti/", "meaning": "n. 城市", "example_en": "I live in the city.", "example_cn": "我住在城市里。"},
        {"word": "town", "phonetic": "/taʊn/", "meaning": "n. 镇", "example_en": "It is a small town.", "example_cn": "这是一个小镇。"},
        {"word": "village", "phonetic": "/ˈvɪlɪdʒ/", "meaning": "n. 村庄", "example_en": "They live in a village.", "example_cn": "他们住在村庄里。"},
        {"word": "country", "phonetic": "/ˈkʌntri/", "meaning": "n. 国家", "example_en": "Which country are you from?", "example_cn": "你来自哪个国家？"},
        {"word": "road", "phonetic": "/roʊd/", "meaning": "n. 路", "example_en": "Cross the road carefully.", "example_cn": "小心过马路。"},
        {"word": "park", "phonetic": "/pɑːrk/", "meaning": "n. 公园", "example_en": "Let's go to the park.", "example_cn": "我们去公园吧。"},
        {"word": "school", "phonetic": "/skuːl/", "meaning": "n. 学校", "example_en": "Walk to school.", "example_cn": "走路去学校。"},
        {"word": "bank", "phonetic": "/bæŋk/", "meaning": "n. 银行", "example_en": "Where is the bank?", "example_cn": "银行在哪里？"},
        {"word": "post", "phonetic": "/poʊst/", "meaning": "n. 邮局", "example_en": "Go to the post office.", "example_cn": "去趟邮局。"},
        {"word": "market", "phonetic": "/ˈmɑːrkɪt/", "meaning": "n. 市场", "example_en": "Buy it at the market.", "example_cn": "在市场买吧。"},
        {"word": "mall", "phonetic": "/mɔːl/", "meaning": "n. 购物中心", "example_en": "Let's go to the mall.", "example_cn": "我们去商场吧。"},
        {"word": "gym", "phonetic": "/dʒɪm/", "meaning": "n. 健身房", "example_en": "I go to the gym.", "example_cn": "我去健身房。"},
        {"word": "library", "phonetic": "/ˈlaɪbreri/", "meaning": "n. 图书馆", "example_en": "Study in the library.", "example_cn": "在图书馆学习。"},
        {"word": "museum", "phonetic": "/mjuˈziːəm/", "meaning": "n. 博物馆", "example_en": "Visit the museum.", "example_cn": "参观博物馆。"},
        {"word": "church", "phonetic": "/tʃɜːrtʃ/", "meaning": "n. 教堂", "example_en": "The church is old.", "example_cn": "那座教堂很古老。"},
        {"word": "theater", "phonetic": "/ˈθiːətər/", "meaning": "n. 剧院", "example_en": "Go to the theater.", "example_cn": "去剧院。"},
        {"word": "cinema", "phonetic": "/ˈsɪnəmə/", "meaning": "n. 电影院", "example_en": "Watch a movie at the cinema.", "example_cn": "在电影院看电影。"},
        {"word": "beach", "phonetic": "/biːtʃ/", "meaning": "n. 海滩", "example_en": "Walk on the beach.", "example_cn": "在海滩上散步。"},
        {"word": "mountain", "phonetic": "/ˈmaʊntn/", "meaning": "n. 山", "example_en": "Climb the mountain.", "example_cn": "爬山。"},
        {"word": "river", "phonetic": "/ˈrɪvər/", "meaning": "n. 河", "example_en": "Swim in the river.", "example_cn": "在河里游泳。"},
        {"word": "lake", "phonetic": "/leɪk/", "meaning": "n. 湖", "example_en": "The lake is beautiful.", "example_cn": "这片湖很美。"},
        {"word": "tree", "phonetic": "/triː/", "meaning": "n. 树", "example_en": "Look at the tree.", "example_cn": "看那棵树。"},
        {"word": "flower", "phonetic": "/ˈflaʊər/", "meaning": "n. 花", "example_en": "Smell the flower.", "example_cn": "闻一闻花香。"},
        {"word": "grass", "phonetic": "/ɡræs/", "meaning": "n. 草", "example_en": "Sit on the grass.", "example_cn": "坐在草地上。"},
        {"word": "leaf", "phonetic": "/liːf/", "meaning": "n. 树叶", "example_en": "A green leaf.", "example_cn": "一片绿叶。"},
        {"word": "animal", "phonetic": "/ˈænɪml/", "meaning": "n. 动物", "example_en": "I like animals.", "example_cn": "我喜欢动物。"},
        {"word": "dog", "phonetic": "/dɔːɡ/", "meaning": "n. 狗", "example_en": "Walk the dog.", "example_cn": "遛狗。"},
        {"word": "cat", "phonetic": "/kæt/", "meaning": "n. 猫", "example_en": "Feed the cat.", "example_cn": "喂猫。"},
        {"word": "bird", "phonetic": "/bɜːrd/", "meaning": "n. 鸟", "example_en": "The bird flies.", "example_cn": "鸟在飞。"},
        {"word": "house", "phonetic": "/haʊs/", "meaning": "n. 房子", "example_en": "This is my house.", "example_cn": "这是我的房子。"},
        {"word": "home", "phonetic": "/hoʊm/", "meaning": "n. 家", "example_en": "Go home.", "example_cn": "回家。"},
        {"word": "room", "phonetic": "/ruːm/", "meaning": "n. 房间", "example_en": "Clean your room.", "example_cn": "打扫你的房间。"},
        {"word": "living", "phonetic": "/ˈlɪvɪŋ/", "meaning": "n. 客厅", "example_en": "Sit in the living room.", "example_cn": "坐在客厅里。"},
        {"word": "wall", "phonetic": "/wɔːl/", "meaning": "n. 墙壁", "example_en": "Paint the wall.", "example_cn": "粉刷墙壁。"},
        {"word": "floor", "phonetic": "/flɔːr/", "meaning": "n. 地板", "example_en": "Sweep the floor.", "example_cn": "扫地。"},
        {"word": "ceiling", "phonetic": "/ˈsiːlɪŋ/", "meaning": "n. 天花板", "example_en": "Look at the ceiling.", "example_cn": "看天花板。"},
        {"word": "roof", "phonetic": "/ruːf/", "meaning": "n. 屋顶", "example_en": "Fix the roof.", "example_cn": "修理屋顶。"},
        {"word": "door", "phonetic": "/dɔːr/", "meaning": "n. 门", "example_en": "Knock on the door.", "example_cn": "敲门。"},
        {"word": "window", "phonetic": "/ˈwɪndoʊ/", "meaning": "n. 窗户", "example_en": "Close the window.", "example_cn": "关上窗户。"},
        {"word": "bed", "phonetic": "/bed/", "meaning": "n. 床", "example_en": "Go to bed.", "example_cn": "上床睡觉。"},
        {"word": "chair", "phonetic": "/tʃer/", "meaning": "n. 椅子", "example_en": "Take a chair.", "example_cn": "拿把椅子。"},
        {"word": "table", "phonetic": "/ˈteɪbl/", "meaning": "n. 桌子", "example_en": "Set the table.", "example_cn": "摆好餐桌。"},
        {"word": "desk", "phonetic": "/desk/", "meaning": "n. 书桌", "example_en": "Work at the desk.", "example_cn": "在书桌前工作。"},
        {"word": "lamp", "phonetic": "/læmp/", "meaning": "n. 台灯", "example_en": "Turn on the lamp.", "example_cn": "打开台灯。"},
        {"word": "light", "phonetic": "/laɪt/", "meaning": "n. 灯", "example_en": "Turn off the light.", "example_cn": "关灯。"},
        {"word": "bus", "phonetic": "/bʌs/", "meaning": "n. 公交车", "example_en": "Take the bus.", "example_cn": "坐公交车。"},
        {"word": "car", "phonetic": "/kɑːr/", "meaning": "n. 汽车", "example_en": "Drive a car.", "example_cn": "开车。"},
        {"word": "train", "phonetic": "/treɪn/", "meaning": "n. 火车", "example_en": "Catch the train.", "example_cn": "赶火车。"},
        {"word": "boat", "phonetic": "/boʊt/", "meaning": "n. 船", "example_en": "Rent a boat.", "example_cn": "租一艘船。"},
        {"word": "plane", "phonetic": "/pleɪn/", "meaning": "n. 飞机", "example_en": "Board the plane.", "example_cn": "登机。"},
        {"word": "fly", "phonetic": "/flaɪ/", "meaning": "v. 飞", "example_en": "I will fly there.", "example_cn": "我会飞过去。"},
        {"word": "walk", "phonetic": "/wɔːk/", "meaning": "v. 走", "example_en": "Let's walk.", "example_cn": "我们走吧。"},
        {"word": "run", "phonetic": "/rʌn/", "meaning": "v. 跑", "example_en": "Run fast.", "example_cn": "快跑。"},
        {"word": "cross", "phonetic": "/krɔːs/", "meaning": "v. 穿过", "example_en": "Cross the street.", "example_cn": "过马路。"},
        {"word": "seat", "phonetic": "/siːt/", "meaning": "n. 座位", "example_en": "Take a seat.", "example_cn": "请坐。"},
        {"word": "day", "phonetic": "/deɪ/", "meaning": "n. 天", "example_en": "Have a nice day.", "example_cn": "祝你今天愉快。"},
        {"word": "night", "phonetic": "/naɪt/", "meaning": "n. 夜晚", "example_en": "Good night.", "example_cn": "晚安。"},
        {"word": "morning", "phonetic": "/ˈmɔːrnɪŋ/", "meaning": "n. 早晨", "example_en": "Good morning.", "example_cn": "早上好。"},
        {"word": "afternoon", "phonetic": "/ˌæftərˈnuːn/", "meaning": "n. 下午", "example_en": "Good afternoon.", "example_cn": "下午好。"},
        {"word": "evening", "phonetic": "/ˈiːvnɪŋ/", "meaning": "n. 晚上", "example_en": "Good evening.", "example_cn": "晚上好。"},
        {"word": "hour", "phonetic": "/ˈaʊər/", "meaning": "n. 小时", "example_en": "One hour left.", "example_cn": "还剩一个小时。"},
        {"word": "minute", "phonetic": "/ˈmɪnɪt/", "meaning": "n. 分钟", "example_en": "Wait a minute.", "example_cn": "等一分钟。"},
        {"word": "second", "phonetic": "/ˈsekənd/", "meaning": "n. 秒", "example_en": "Just a second.", "example_cn": "稍等一秒。"},
        {"word": "year", "phonetic": "/jɪr/", "meaning": "n. 年", "example_en": "Happy New Year.", "example_cn": "新年快乐。"},
        {"word": "weather", "phonetic": "/ˈweðər/", "meaning": "n. 天气", "example_en": "Nice weather.", "example_cn": "好天气。"},
        {"word": "sun", "phonetic": "/sʌn/", "meaning": "n. 太阳", "example_en": "The sun is hot.", "example_cn": "太阳很热。"},
        {"word": "rain", "phonetic": "/reɪn/", "meaning": "n. 雨", "example_en": "It is raining.", "example_cn": "在下雨。"},
        {"word": "snow", "phonetic": "/snoʊ/", "meaning": "n. 雪", "example_en": "It is snowing.", "example_cn": "在下雪。"},
        {"word": "wind", "phonetic": "/wɪnd/", "meaning": "n. 风", "example_en": "Strong wind.", "example_cn": "大风。"},
        {"word": "cloud", "phonetic": "/klaʊd/", "meaning": "n. 云", "example_en": "Look at the cloud.", "example_cn": "看那朵云。"},
        {"word": "clear", "phonetic": "/klɪr/", "meaning": "adj. 晴朗的", "example_en": "The sky is clear.", "example_cn": "天空很晴朗。"},
        {"word": "dark", "phonetic": "/dɑːrk/", "meaning": "adj. 黑的", "example_en": "It is dark outside.", "example_cn": "外面很黑。"},
        {"word": "bright", "phonetic": "/braɪt/", "meaning": "adj. 明亮的", "example_en": "The light is bright.", "example_cn": "光线很亮。"},
        {"word": "feel", "phonetic": "/fiːl/", "meaning": "v. 感觉", "example_en": "How do you feel?", "example_cn": "你感觉怎么样？"},
        {"word": "happy", "phonetic": "/ˈhæpi/", "meaning": "adj. 开心的", "example_en": "I am happy.", "example_cn": "我很开心。"},
        {"word": "sad", "phonetic": "/sæd/", "meaning": "adj. 难过的", "example_en": "Don't be sad.", "example_cn": "别难过。"},
        {"word": "angry", "phonetic": "/ˈæŋɡri/", "meaning": "adj. 生气的", "example_en": "Are you angry?", "example_cn": "你生气了吗？"},
        {"word": "tired", "phonetic": "/ˈtaɪərd/", "meaning": "adj. 累的", "example_en": "I am so tired.", "example_cn": "我太累了。"},
        {"word": "busy", "phonetic": "/ˈbɪzi/", "meaning": "adj. 忙的", "example_en": "I am very busy.", "example_cn": "我很忙。"},
        {"word": "free", "phonetic": "/friː/", "meaning": "adj. 有空的", "example_en": "Are you free now?", "example_cn": "你现在有空吗？"},
        {"word": "good", "phonetic": "/ɡʊd/", "meaning": "adj. 好的", "example_en": "This is good.", "example_cn": "这很好。"},
        {"word": "bad", "phonetic": "/bæd/", "meaning": "adj. 坏的", "example_en": "That is bad.", "example_cn": "那很糟糕。"},
        {"word": "right", "phonetic": "/raɪt/", "meaning": "adj. 对的", "example_en": "You are right.", "example_cn": "你是对的。"},
        {"word": "wrong", "phonetic": "/rɔːŋ/", "meaning": "adj. 错的", "example_en": "That is wrong.", "example_cn": "那是错的。"},
        {"word": "true", "phonetic": "/truː/", "meaning": "adj. 真的", "example_en": "Is it true?", "example_cn": "这是真的吗？"},
        {"word": "false", "phonetic": "/fɔːls/", "meaning": "adj. 假的", "example_en": "That is false.", "example_cn": "那是假的。"},
        {"word": "big", "phonetic": "/bɪɡ/", "meaning": "adj. 大的", "example_en": "A big dog.", "example_cn": "一只大狗。"},
        {"word": "small", "phonetic": "/smɔːl/", "meaning": "adj. 小的", "example_en": "A small room.", "example_cn": "一个小房间。"},
        {"word": "long", "phonetic": "/lɔːŋ/", "meaning": "adj. 长的", "example_en": "A long time.", "example_cn": "很长时间。"},
        {"word": "short", "phonetic": "/ʃɔːrt/", "meaning": "adj. 短的", "example_en": "A short break.", "example_cn": "短暂的休息。"},
        {"word": "high", "phonetic": "/haɪ/", "meaning": "adj. 高的", "example_en": "A high mountain.", "example_cn": "一座高山。"},
        {"word": "low", "phonetic": "/loʊ/", "meaning": "adj. 低的", "example_en": "Low price.", "example_cn": "低价格。"},
        {"word": "fast", "phonetic": "/fæst/", "meaning": "adj. 快的", "example_en": "Run fast.", "example_cn": "跑得快。"},
        {"word": "slow", "phonetic": "/sloʊ/", "meaning": "adj. 慢的", "example_en": "Drive slow.", "example_cn": "开慢点。"},
        {"word": "far", "phonetic": "/fɑːr/", "meaning": "adj. 远的", "example_en": "Is it far?", "example_cn": "远吗？"},
        {"word": "near", "phonetic": "/nɪr/", "meaning": "adj. 近的", "example_en": "It is very near.", "example_cn": "非常近。"},
        {"word": "here", "phonetic": "/hɪr/", "meaning": "adv. 这里", "example_en": "Come here.", "example_cn": "来这里。"},
        {"word": "there", "phonetic": "/ðer/", "meaning": "adv. 那里", "example_en": "Go there.", "example_cn": "去那里。"},
        {"word": "place", "phonetic": "/pleɪs/", "meaning": "n. 地方", "example_en": "A nice place.", "example_cn": "一个好地方。"}
    ],

    # ==========================================
    # 📱 Level 7: 海外生存 - 数字、方位与日常科技 (100词)
    # ==========================================
    7: [
        {"word": "computer", "phonetic": "/kəmˈpjuːtər/", "meaning": "n. 电脑", "example_en": "Turn on the computer.", "example_cn": "打开电脑。"},
        {"word": "internet", "phonetic": "/ˈɪntərnet/", "meaning": "n. 互联网", "example_en": "No internet connection.", "example_cn": "没有网络连接。"},
        {"word": "wifi", "phonetic": "/ˈwaɪfaɪ/", "meaning": "n. 无线网", "example_en": "What is the wifi password?", "example_cn": "无线网密码是多少？"},
        {"word": "password", "phonetic": "/ˈpæswɜːrd/", "meaning": "n. 密码", "example_en": "Enter your password.", "example_cn": "输入你的密码。"},
        {"word": "email", "phonetic": "/ˈiːmeɪl/", "meaning": "n. 电子邮件", "example_en": "Send me an email.", "example_cn": "发邮件给我。"},
        {"word": "message", "phonetic": "/ˈmesɪdʒ/", "meaning": "n. 消息", "example_en": "Leave a message.", "example_cn": "留个言吧。"},
        {"word": "text", "phonetic": "/tekst/", "meaning": "v. 发短信", "example_en": "Text me later.", "example_cn": "晚点发短信给我。"},
        {"word": "photo", "phonetic": "/ˈfoʊtoʊ/", "meaning": "n. 照片", "example_en": "Take a photo.", "example_cn": "拍张照片。"},
        {"word": "video", "phonetic": "/ˈvɪdioʊ/", "meaning": "n. 视频", "example_en": "Watch this video.", "example_cn": "看这个视频。"},
        {"word": "camera", "phonetic": "/ˈkæmərə/", "meaning": "n. 相机", "example_en": "Smile for the camera.", "example_cn": "对着相机笑一个。"},
        {"word": "music", "phonetic": "/ˈmjuːzɪk/", "meaning": "n. 音乐", "example_en": "Listen to music.", "example_cn": "听音乐。"},
        {"word": "song", "phonetic": "/sɔːŋ/", "meaning": "n. 歌曲", "example_en": "Sing a song.", "example_cn": "唱首歌。"},
        {"word": "game", "phonetic": "/ɡeɪm/", "meaning": "n. 游戏", "example_en": "Play a game.", "example_cn": "玩个游戏。"},
        {"word": "app", "phonetic": "/æp/", "meaning": "n. 软件", "example_en": "Download this app.", "example_cn": "下载这个软件。"},
        {"word": "website", "phonetic": "/ˈwebsaɪt/", "meaning": "n. 网站", "example_en": "Check the website.", "example_cn": "查看那个网站。"},
        {"word": "link", "phonetic": "/lɪŋk/", "meaning": "n. 链接", "example_en": "Click the link.", "example_cn": "点击链接。"},
        {"word": "screen", "phonetic": "/skriːn/", "meaning": "n. 屏幕", "example_en": "Touch the screen.", "example_cn": "触摸屏幕。"},
        {"word": "keyboard", "phonetic": "/ˈkiːbɔːrd/", "meaning": "n. 键盘", "example_en": "Use the keyboard.", "example_cn": "使用键盘。"},
        {"word": "mouse", "phonetic": "/maʊs/", "meaning": "n. 鼠标", "example_en": "Click the mouse.", "example_cn": "点击鼠标。"},
        {"word": "cable", "phonetic": "/ˈkeɪbl/", "meaning": "n. 线缆", "example_en": "Plug in the cable.", "example_cn": "插上线缆。"},
        {"word": "document", "phonetic": "/ˈdɑːkjumənt/", "meaning": "n. 文件", "example_en": "Sign the document.", "example_cn": "签署文件。"},
        {"word": "file", "phonetic": "/faɪl/", "meaning": "n. 档案", "example_en": "Save the file.", "example_cn": "保存档案。"},
        {"word": "copy", "phonetic": "/ˈkɑːpi/", "meaning": "v. 复制", "example_en": "Copy this page.", "example_cn": "复制这一页。"},
        {"word": "print", "phonetic": "/prɪnt/", "meaning": "v. 打印", "example_en": "Print the ticket.", "example_cn": "打印票据。"},
        {"word": "machine", "phonetic": "/məˈʃiːn/", "meaning": "n. 机器", "example_en": "The machine is broken.", "example_cn": "机器坏了。"},
        {"word": "tool", "phonetic": "/tuːl/", "meaning": "n. 工具", "example_en": "I need a tool.", "example_cn": "我需要一个工具。"},
        {"word": "hammer", "phonetic": "/ˈhæmər/", "meaning": "n. 锤子", "example_en": "Use a hammer.", "example_cn": "用锤子。"},
        {"word": "nail", "phonetic": "/neɪl/", "meaning": "n. 钉子", "example_en": "Hit the nail.", "example_cn": "敲钉子。"},
        {"word": "tape", "phonetic": "/teɪp/", "meaning": "n. 胶带", "example_en": "Use some tape.", "example_cn": "用点胶带。"},
        {"word": "glue", "phonetic": "/ɡluː/", "meaning": "n. 胶水", "example_en": "Need some glue.", "example_cn": "需要些胶水。"},
        {"word": "string", "phonetic": "/strɪŋ/", "meaning": "n. 细绳", "example_en": "Tie the string.", "example_cn": "系上细绳。"},
        {"word": "rope", "phonetic": "/roʊp/", "meaning": "n. 粗绳", "example_en": "Pull the rope.", "example_cn": "拉紧绳子。"},
        {"word": "wire", "phonetic": "/waɪr/", "meaning": "n. 电线", "example_en": "Don't touch the wire.", "example_cn": "别碰电线。"},
        {"word": "switch", "phonetic": "/swɪtʃ/", "meaning": "n. 开关", "example_en": "Press the switch.", "example_cn": "按开关。"},
        {"word": "button", "phonetic": "/ˈbʌtn/", "meaning": "n. 按钮", "example_en": "Push the red button.", "example_cn": "按下红色的按钮。"},
        {"word": "fan", "phonetic": "/fæn/", "meaning": "n. 风扇", "example_en": "Turn on the fan.", "example_cn": "打开风扇。"},
        {"word": "heater", "phonetic": "/ˈhiːtər/", "meaning": "n. 取暖器", "example_en": "The heater is on.", "example_cn": "取暖器开着。"},
        {"word": "sheet", "phonetic": "/ʃiːt/", "meaning": "n. 床单", "example_en": "Change the sheets.", "example_cn": "换床单。"},
        {"word": "sponge", "phonetic": "/spʌndʒ/", "meaning": "n. 海绵", "example_en": "Wash it with a sponge.", "example_cn": "用海绵洗它。"},
        {"word": "bucket", "phonetic": "/ˈbʌkɪt/", "meaning": "n. 水桶", "example_en": "Fill the bucket.", "example_cn": "把水桶装满。"},
        {"word": "up", "phonetic": "/ʌp/", "meaning": "adv. 向上", "example_en": "Look up.", "example_cn": "向上看。"},
        {"word": "down", "phonetic": "/daʊn/", "meaning": "adv. 向下", "example_en": "Sit down.", "example_cn": "坐下。"},
        {"word": "in", "phonetic": "/ɪn/", "meaning": "prep. 在...里", "example_en": "Come in.", "example_cn": "进来。"},
        {"word": "out", "phonetic": "/aʊt/", "meaning": "adv. 在外面", "example_en": "Go out.", "example_cn": "出去。"},
        {"word": "on", "phonetic": "/ɑːn/", "meaning": "prep. 在...上", "example_en": "Put it on the table.", "example_cn": "把它放在桌上。"},
        {"word": "off", "phonetic": "/ɔːf/", "meaning": "adv. 离开，关闭", "example_en": "Turn it off.", "example_cn": "把它关掉。"},
        {"word": "over", "phonetic": "/ˈoʊvər/", "meaning": "prep. 在...上方", "example_en": "Jump over it.", "example_cn": "跳过它。"},
        {"word": "under", "phonetic": "/ˈʌndər/", "meaning": "prep. 在...下方", "example_en": "Look under the bed.", "example_cn": "看看床下。"},
        {"word": "above", "phonetic": "/əˈbʌv/", "meaning": "prep. 在...之上", "example_en": "The sky above us.", "example_cn": "我们上方的天空。"},
        {"word": "below", "phonetic": "/bɪˈloʊ/", "meaning": "prep. 在...之下", "example_en": "See below.", "example_cn": "见下文。"},
        {"word": "front", "phonetic": "/frʌnt/", "meaning": "n. 前面", "example_en": "In front of the house.", "example_cn": "在房子前面。"},
        {"word": "back", "phonetic": "/bæk/", "meaning": "n. 后面", "example_en": "Go to the back.", "example_cn": "去后面。"},
        {"word": "next", "phonetic": "/nekst/", "meaning": "adj. 下一个", "example_en": "Next one, please.", "example_cn": "请下一位。"},
        {"word": "beside", "phonetic": "/bɪˈsaɪd/", "meaning": "prep. 在...旁边", "example_en": "Sit beside me.", "example_cn": "坐在我旁边。"},
        {"word": "behind", "phonetic": "/bɪˈhaɪnd/", "meaning": "prep. 在...后面", "example_en": "Look behind you.", "example_cn": "看你后面。"},
        {"word": "between", "phonetic": "/bɪˈtwiːn/", "meaning": "prep. 在...之间", "example_en": "Read between the lines.", "example_cn": "体会言外之意。"},
        {"word": "center", "phonetic": "/ˈsentər/", "meaning": "n. 中心", "example_en": "In the city center.", "example_cn": "在市中心。"},
        {"word": "middle", "phonetic": "/ˈmɪdl/", "meaning": "n. 中间", "example_en": "In the middle of the night.", "example_cn": "在半夜。"},
        {"word": "side", "phonetic": "/saɪd/", "meaning": "n. 侧面", "example_en": "On the left side.", "example_cn": "在左侧。"},
        {"word": "edge", "phonetic": "/edʒ/", "meaning": "n. 边缘", "example_en": "Don't stand on the edge.", "example_cn": "别站在边缘。"},
        {"word": "zero", "phonetic": "/ˈzɪroʊ/", "meaning": "num. 零", "example_en": "Start from zero.", "example_cn": "从零开始。"},
        {"word": "one", "phonetic": "/wʌn/", "meaning": "num. 一", "example_en": "Just one.", "example_cn": "只要一个。"},
        {"word": "two", "phonetic": "/tuː/", "meaning": "num. 二", "example_en": "Table for two.", "example_cn": "两人位。"},
        {"word": "three", "phonetic": "/θriː/", "meaning": "num. 三", "example_en": "Three times.", "example_cn": "三次。"},
        {"word": "four", "phonetic": "/fɔːr/", "meaning": "num. 四", "example_en": "Four people.", "example_cn": "四个人。"},
        {"word": "five", "phonetic": "/faɪv/", "meaning": "num. 五", "example_en": "High five!", "example_cn": "击掌！"},
        {"word": "six", "phonetic": "/sɪks/", "meaning": "num. 六", "example_en": "Six days.", "example_cn": "六天。"},
        {"word": "seven", "phonetic": "/ˈsevn/", "meaning": "num. 七", "example_en": "Seven hours.", "example_cn": "七小时。"},
        {"word": "eight", "phonetic": "/eɪt/", "meaning": "num. 八", "example_en": "Eight dollars.", "example_cn": "八美元。"},
        {"word": "nine", "phonetic": "/naɪn/", "meaning": "num. 九", "example_en": "Nine months.", "example_cn": "九个月。"},
        {"word": "ten", "phonetic": "/ten/", "meaning": "num. 十", "example_en": "Top ten.", "example_cn": "前十名。"},
        {"word": "first", "phonetic": "/fɜːrst/", "meaning": "adj. 第一", "example_en": "The first time.", "example_cn": "第一次。"},
        {"word": "last", "phonetic": "/læst/", "meaning": "adj. 最后", "example_en": "The last train.", "example_cn": "末班车。"},
        {"word": "half", "phonetic": "/hæf/", "meaning": "n. 一半", "example_en": "Half an hour.", "example_cn": "半小时。"},
        {"word": "pair", "phonetic": "/per/", "meaning": "n. 一双", "example_en": "A pair of shoes.", "example_cn": "一双鞋。"},
        {"word": "piece", "phonetic": "/piːs/", "meaning": "n. 一块", "example_en": "A piece of cake.", "example_cn": "一块蛋糕。"},
        {"word": "group", "phonetic": "/ɡruːp/", "meaning": "n. 组", "example_en": "Work in a group.", "example_cn": "小组工作。"},
        {"word": "single", "phonetic": "/ˈsɪŋɡl/", "meaning": "adj. 单个的", "example_en": "A single room.", "example_cn": "单人房。"},
        {"word": "double", "phonetic": "/ˈdʌbl/", "meaning": "adj. 双倍的", "example_en": "A double bed.", "example_cn": "双人床。"},
        {"word": "bunch", "phonetic": "/bʌntʃ/", "meaning": "n. 一束", "example_en": "A bunch of flowers.", "example_cn": "一束花。"},
        {"word": "red", "phonetic": "/red/", "meaning": "adj. 红色", "example_en": "A red car.", "example_cn": "一辆红色的车。"},
        {"word": "blue", "phonetic": "/bluː/", "meaning": "adj. 蓝色", "example_en": "Blue sky.", "example_cn": "蓝天。"},
        {"word": "green", "phonetic": "/ɡriːn/", "meaning": "adj. 绿色", "example_en": "Green tea.", "example_cn": "绿茶。"},
        {"word": "yellow", "phonetic": "/ˈjeloʊ/", "meaning": "adj. 黄色", "example_en": "A yellow shirt.", "example_cn": "一件黄色的衬衫。"},
        {"word": "black", "phonetic": "/blæk/", "meaning": "adj. 黑色", "example_en": "Black coffee.", "example_cn": "黑咖啡。"},
        {"word": "white", "phonetic": "/waɪt/", "meaning": "adj. 白色", "example_en": "White paper.", "example_cn": "白纸。"},
        {"word": "brown", "phonetic": "/braʊn/", "meaning": "adj. 棕色", "example_en": "Brown hair.", "example_cn": "棕色的头发。"},
        {"word": "grey", "phonetic": "/ɡreɪ/", "meaning": "adj. 灰色", "example_en": "Grey clouds.", "example_cn": "灰色的云。"},
        {"word": "pink", "phonetic": "/pɪŋk/", "meaning": "adj. 粉色", "example_en": "A pink dress.", "example_cn": "一条粉色的裙子。"},
        {"word": "orange", "phonetic": "/ˈɔːrɪndʒ/", "meaning": "adj. 橙色", "example_en": "Orange juice.", "example_cn": "橙汁。"},
        {"word": "purple", "phonetic": "/ˈpɜːrpl/", "meaning": "adj. 紫色", "example_en": "A purple bag.", "example_cn": "一个紫色的包。"},
        {"word": "silver", "phonetic": "/ˈsɪlvər/", "meaning": "adj. 银色", "example_en": "A silver ring.", "example_cn": "一枚银戒指。"},
        {"word": "gold", "phonetic": "/ɡoʊld/", "meaning": "adj. 金色", "example_en": "A gold watch.", "example_cn": "一块金表。"},
        {"word": "clear", "phonetic": "/klɪr/", "meaning": "adj. 清楚的", "example_en": "Make it clear.", "example_cn": "把它弄清楚。"},
        {"word": "bright", "phonetic": "/braɪt/", "meaning": "adj. 明亮的", "example_en": "Very bright.", "example_cn": "非常亮。"},
        {"word": "dark", "phonetic": "/dɑːrk/", "meaning": "adj. 黑暗的", "example_en": "Too dark.", "example_cn": "太黑了。"},
        {"word": "light", "phonetic": "/laɪt/", "meaning": "adj. 浅色的", "example_en": "Light blue.", "example_cn": "浅蓝色。"},
        {"word": "shape", "phonetic": "/ʃeɪp/", "meaning": "n. 形状", "example_en": "What shape is it?", "example_cn": "它是什么形状的？"},
        {"word": "circle", "phonetic": "/ˈsɜːrkl/", "meaning": "n. 圆圈", "example_en": "Draw a circle.", "example_cn": "画个圆。"},
        {"word": "square", "phonetic": "/skwer/", "meaning": "n. 正方形", "example_en": "A square box.", "example_cn": "一个方形盒子。"}
    ],

    # ==========================================
    # 👨‍⚕️ Level 8: 海外生存 - 人物、时间与常用动作 (100词)
    # ==========================================
    8: [
        {"word": "man", "phonetic": "/mæn/", "meaning": "n. 男人", "example_en": "He is a good man.", "example_cn": "他是个好人。"},
        {"word": "woman", "phonetic": "/ˈwʊmən/", "meaning": "n. 女人", "example_en": "A smart woman.", "example_cn": "一个聪明的女人。"},
        {"word": "boy", "phonetic": "/bɔɪ/", "meaning": "n. 男孩", "example_en": "The boy is crying.", "example_cn": "那个男孩在哭。"},
        {"word": "girl", "phonetic": "/ɡɜːrl/", "meaning": "n. 女孩", "example_en": "A cute girl.", "example_cn": "一个可爱的女孩。"},
        {"word": "child", "phonetic": "/tʃaɪld/", "meaning": "n. 孩子", "example_en": "She is a child.", "example_cn": "她是个孩子。"},
        {"word": "adult", "phonetic": "/əˈdʌlt/", "meaning": "n. 成年人", "example_en": "Only for adults.", "example_cn": "仅限成人。"},
        {"word": "baby", "phonetic": "/ˈbeɪbi/", "meaning": "n. 婴儿", "example_en": "A newborn baby.", "example_cn": "一个新生婴儿。"},
        {"word": "person", "phonetic": "/ˈpɜːrsn/", "meaning": "n. 人", "example_en": "A nice person.", "example_cn": "一个好人。"},
        {"word": "people", "phonetic": "/ˈpiːpl/", "meaning": "n. 人们", "example_en": "Many people here.", "example_cn": "这里有很多人。"},
        {"word": "manager", "phonetic": "/ˈmænɪdʒər/", "meaning": "n. 经理", "example_en": "Call the manager.", "example_cn": "叫经理来。"},
        {"word": "teacher", "phonetic": "/ˈtiːtʃər/", "meaning": "n. 老师", "example_en": "Ask the teacher.", "example_cn": "问老师。"},
        {"word": "student", "phonetic": "/ˈstuːdnt/", "meaning": "n. 学生", "example_en": "He is a student.", "example_cn": "他是个学生。"},
        {"word": "dentist", "phonetic": "/ˈdentɪst/", "meaning": "n. 牙医", "example_en": "I need a dentist.", "example_cn": "我需要看牙医。"},
        {"word": "nurse", "phonetic": "/nɜːrs/", "meaning": "n. 护士", "example_en": "The nurse is kind.", "example_cn": "那个护士很善良。"},
        {"word": "driver", "phonetic": "/ˈdraɪvər/", "meaning": "n. 司机", "example_en": "A taxi driver.", "example_cn": "一个出租车司机。"},
        {"word": "worker", "phonetic": "/ˈwɜːrkər/", "meaning": "n. 工人", "example_en": "A hard worker.", "example_cn": "一个努力的工人。"},
        {"word": "farmer", "phonetic": "/ˈfɑːrmər/", "meaning": "n. 农民", "example_en": "The farmer is busy.", "example_cn": "农民很忙。"},
        {"word": "clerk", "phonetic": "/klɜːrk/", "meaning": "n. 职员", "example_en": "Ask the clerk.", "example_cn": "去问那个职员。"},
        {"word": "staff", "phonetic": "/stæf/", "meaning": "n. 员工", "example_en": "Hotel staff.", "example_cn": "酒店员工。"},
        {"word": "owner", "phonetic": "/ˈoʊnər/", "meaning": "n. 拥有者", "example_en": "The shop owner.", "example_cn": "店主。"},
        {"word": "Monday", "phonetic": "/ˈmʌndeɪ/", "meaning": "n. 星期一", "example_en": "See you on Monday.", "example_cn": "周一见。"},
        {"word": "Tuesday", "phonetic": "/ˈtuːzdeɪ/", "meaning": "n. 星期二", "example_en": "Next Tuesday.", "example_cn": "下周二。"},
        {"word": "Wednesday", "phonetic": "/ˈwenzdeɪ/", "meaning": "n. 星期三", "example_en": "Every Wednesday.", "example_cn": "每个周三。"},
        {"word": "Thursday", "phonetic": "/ˈθɜːrzdeɪ/", "meaning": "n. 星期四", "example_en": "I'm free on Thursday.", "example_cn": "我周四有空。"},
        {"word": "Friday", "phonetic": "/ˈfraɪdeɪ/", "meaning": "n. 星期五", "example_en": "Happy Friday!", "example_cn": "周五快乐！"},
        {"word": "Saturday", "phonetic": "/ˈsætərdeɪ/", "meaning": "n. 星期六", "example_en": "Saturday morning.", "example_cn": "周六早上。"},
        {"word": "Sunday", "phonetic": "/ˈsʌndeɪ/", "meaning": "n. 星期日", "example_en": "Sunday is a holiday.", "example_cn": "周日是休息日。"},
        {"word": "January", "phonetic": "/ˈdʒænjueri/", "meaning": "n. 一月", "example_en": "Born in January.", "example_cn": "一月出生。"},
        {"word": "February", "phonetic": "/ˈfebrueri/", "meaning": "n. 二月", "example_en": "It is cold in February.", "example_cn": "二月很冷。"},
        {"word": "March", "phonetic": "/mɑːrtʃ/", "meaning": "n. 三月", "example_en": "Come in March.", "example_cn": "三月来吧。"},
        {"word": "April", "phonetic": "/ˈeɪprəl/", "meaning": "n. 四月", "example_en": "April showers.", "example_cn": "四月的阵雨。"},
        {"word": "May", "phonetic": "/meɪ/", "meaning": "n. 五月", "example_en": "Leave in May.", "example_cn": "在五月离开。"},
        {"word": "June", "phonetic": "/dʒuːn/", "meaning": "n. 六月", "example_en": "Start in June.", "example_cn": "在六月开始。"},
        {"word": "July", "phonetic": "/dʒuːlaɪ/", "meaning": "n. 七月", "example_en": "Hot in July.", "example_cn": "七月很热。"},
        {"word": "August", "phonetic": "/ˈɔːɡəst/", "meaning": "n. 八月", "example_en": "August is busy.", "example_cn": "八月很忙。"},
        {"word": "September", "phonetic": "/sepˈtembər/", "meaning": "n. 九月", "example_en": "Back to school in September.", "example_cn": "九月开学。"},
        {"word": "October", "phonetic": "/ɑːkˈtoʊbər/", "meaning": "n. 十月", "example_en": "October is beautiful.", "example_cn": "十月很美。"},
        {"word": "November", "phonetic": "/noʊˈvembər/", "meaning": "n. 十一月", "example_en": "Cold in November.", "example_cn": "十一月很冷。"},
        {"word": "December", "phonetic": "/dɪˈsembər/", "meaning": "n. 十二月", "example_en": "December snow.", "example_cn": "十二月的雪。"},
        {"word": "season", "phonetic": "/ˈsiːzn/", "meaning": "n. 季节", "example_en": "Which season?", "example_cn": "哪个季节？"},
        {"word": "spring", "phonetic": "/sprɪŋ/", "meaning": "n. 春天", "example_en": "Spring is coming.", "example_cn": "春天来了。"},
        {"word": "summer", "phonetic": "/ˈsʌmər/", "meaning": "n. 夏天", "example_en": "I love summer.", "example_cn": "我爱夏天。"},
        {"word": "autumn", "phonetic": "/ˈɔːtəm/", "meaning": "n. 秋天", "example_en": "Autumn leaves.", "example_cn": "秋天的落叶。"},
        {"word": "winter", "phonetic": "/ˈwɪntər/", "meaning": "n. 冬天", "example_en": "Winter is cold.", "example_cn": "冬天很冷。"},
        {"word": "cool", "phonetic": "/kuːl/", "meaning": "adj. 凉爽的", "example_en": "It is cool today.", "example_cn": "今天很凉爽。"},
        {"word": "freeze", "phonetic": "/friːz/", "meaning": "v. 结冰", "example_en": "The water will freeze.", "example_cn": "水会结冰。"},
        {"word": "melt", "phonetic": "/melt/", "meaning": "v. 融化", "example_en": "The ice is melting.", "example_cn": "冰正在融化。"},
        {"word": "storm", "phonetic": "/stɔːrm/", "meaning": "n. 暴风雨", "example_en": "A big storm.", "example_cn": "一场大暴风雨。"},
        {"word": "fog", "phonetic": "/fɔːɡ/", "meaning": "n. 雾", "example_en": "Thick fog.", "example_cn": "浓雾。"},
        {"word": "ice", "phonetic": "/aɪs/", "meaning": "n. 冰", "example_en": "Need some ice.", "example_cn": "需要一些冰。"},
        {"word": "star", "phonetic": "/stɑːr/", "meaning": "n. 星星", "example_en": "Look at the star.", "example_cn": "看那颗星。"},
        {"word": "moon", "phonetic": "/muːn/", "meaning": "n. 月亮", "example_en": "The moon is bright.", "example_cn": "月亮很亮。"},
        {"word": "earth", "phonetic": "/ɜːrθ/", "meaning": "n. 地球", "example_en": "Our earth.", "example_cn": "我们的地球。"},
        {"word": "world", "phonetic": "/wɜːrld/", "meaning": "n. 世界", "example_en": "Around the world.", "example_cn": "环游世界。"},
        {"word": "ground", "phonetic": "/ɡraʊnd/", "meaning": "n. 地面", "example_en": "On the ground.", "example_cn": "在地上。"},
        {"word": "dirt", "phonetic": "/dɜːrt/", "meaning": "n. 泥土", "example_en": "Wash off the dirt.", "example_cn": "洗掉泥土。"},
        {"word": "sand", "phonetic": "/sænd/", "meaning": "n. 沙子", "example_en": "Play in the sand.", "example_cn": "在沙里玩。"},
        {"word": "rock", "phonetic": "/rɑːk/", "meaning": "n. 岩石", "example_en": "A heavy rock.", "example_cn": "一块重石头。"},
        {"word": "stone", "phonetic": "/stoʊn/", "meaning": "n. 石头", "example_en": "Throw a stone.", "example_cn": "扔石头。"},
        {"word": "fire", "phonetic": "/faɪr/", "meaning": "n. 火", "example_en": "Make a fire.", "example_cn": "生火。"},
        {"word": "start", "phonetic": "/stɑːrt/", "meaning": "v. 开始", "example_en": "Start now.", "example_cn": "现在开始。"},
        {"word": "finish", "phonetic": "/ˈfɪnɪʃ/", "meaning": "v. 完成", "example_en": "Finish your work.", "example_cn": "完成你的工作。"},
        {"word": "begin", "phonetic": "/bɪˈɡɪn/", "meaning": "v. 开始", "example_en": "Let's begin.", "example_cn": "我们开始吧。"},
        {"word": "end", "phonetic": "/end/", "meaning": "v. 结束", "example_en": "The movie ends.", "example_cn": "电影结束了。"},
        {"word": "hold", "phonetic": "/hoʊld/", "meaning": "v. 拿着", "example_en": "Hold my hand.", "example_cn": "握住我的手。"},
        {"word": "keep", "phonetic": "/kiːp/", "meaning": "v. 保持", "example_en": "Keep quiet.", "example_cn": "保持安静。"},
        {"word": "bring", "phonetic": "/brɪŋ/", "meaning": "v. 带来", "example_en": "Bring me a cup.", "example_cn": "给我拿个杯子来。"},
        {"word": "take", "phonetic": "/teɪk/", "meaning": "v. 带走", "example_en": "Take it away.", "example_cn": "把它拿走。"},
        {"word": "catch", "phonetic": "/kætʃ/", "meaning": "v. 抓住", "example_en": "Catch the ball.", "example_cn": "抓住球。"},
        {"word": "throw", "phonetic": "/θroʊ/", "meaning": "v. 扔", "example_en": "Throw it away.", "example_cn": "把它扔掉。"},
        {"word": "drop", "phonetic": "/drɑːp/", "meaning": "v. 掉落", "example_en": "Don't drop it.", "example_cn": "别掉在地上。"},
        {"word": "pick", "phonetic": "/pɪk/", "meaning": "v. 拾起", "example_en": "Pick it up.", "example_cn": "把它捡起来。"},
        {"word": "press", "phonetic": "/pres/", "meaning": "v. 按", "example_en": "Press the button.", "example_cn": "按按钮。"},
        {"word": "lift", "phonetic": "/lɪft/", "meaning": "v. 举起", "example_en": "Lift the box.", "example_cn": "举起箱子。"},
        {"word": "scrub", "phonetic": "/skrʌb/", "meaning": "v. 擦洗", "example_en": "Scrub the floor.", "example_cn": "擦洗地板。"},
        {"word": "pack", "phonetic": "/pæk/", "meaning": "v. 打包", "example_en": "Pack your bag.", "example_cn": "把你的包打包好。"},
        {"word": "unpack", "phonetic": "/ˌʌnˈpæk/", "meaning": "v. 拆包", "example_en": "Unpack the box.", "example_cn": "拆开箱子。"},
        {"word": "fix", "phonetic": "/fɪks/", "meaning": "v. 修理", "example_en": "Can you fix it?", "example_cn": "你能修好它吗？"},
        {"word": "break", "phonetic": "/breɪk/", "meaning": "v. 打破", "example_en": "Don't break the glass.", "example_cn": "别打破杯子。"},
        {"word": "build", "phonetic": "/bɪld/", "meaning": "v. 建造", "example_en": "Build a house.", "example_cn": "建一栋房子。"},
        {"word": "destroy", "phonetic": "/dɪˈstrɔɪ/", "meaning": "v. 破坏", "example_en": "Destroy the wall.", "example_cn": "推倒那堵墙。"},
        {"word": "leave", "phonetic": "/liːv/", "meaning": "v. 离开", "example_en": "I have to leave.", "example_cn": "我得走了。"},
        {"word": "stay", "phonetic": "/steɪ/", "meaning": "v. 停留", "example_en": "Stay here.", "example_cn": "待在这儿。"},
        {"word": "stand", "phonetic": "/stænd/", "meaning": "v. 站立", "example_en": "Stand up.", "example_cn": "站起来。"},
        {"word": "sit", "phonetic": "/sɪt/", "meaning": "v. 坐", "example_en": "Sit down.", "example_cn": "坐下。"},
        {"word": "jump", "phonetic": "/dʒʌmp/", "meaning": "v. 跳", "example_en": "Jump high.", "example_cn": "跳高点。"},
        {"word": "fall", "phonetic": "/fɔːl/", "meaning": "v. 摔倒", "example_en": "Don't fall down.", "example_cn": "别摔倒。"},
        {"word": "lay", "phonetic": "/leɪ/", "meaning": "v. 躺下", "example_en": "Lay on the bed.", "example_cn": "躺在床上。"},
        {"word": "rest", "phonetic": "/rest/", "meaning": "v. 休息", "example_en": "Take a rest.", "example_cn": "休息一下。"},
        {"word": "dream", "phonetic": "/driːm/", "meaning": "v. 做梦", "example_en": "Sweet dreams.", "example_cn": "做个好梦。"},
        {"word": "chew", "phonetic": "/tʃuː/", "meaning": "v. 咀嚼", "example_en": "Chew your food.", "example_cn": "咀嚼你的食物。"},
        {"word": "swallow", "phonetic": "/ˈswɑːloʊ/", "meaning": "v. 吞下", "example_en": "Hard to swallow.", "example_cn": "很难咽下去。"},
        {"word": "frown", "phonetic": "/fraʊn/", "meaning": "v. 皱眉", "example_en": "Don't frown.", "example_cn": "别皱眉头。"},
        {"word": "shout", "phonetic": "/ʃaʊt/", "meaning": "v. 大叫", "example_en": "Don't shout.", "example_cn": "别大喊大叫。"},
        {"word": "whisper", "phonetic": "/ˈwɪspər/", "meaning": "v. 低语", "example_en": "Whisper to me.", "example_cn": "对我小声说。"},
        {"word": "hide", "phonetic": "/haɪd/", "meaning": "v. 隐藏", "example_en": "Hide the box.", "example_cn": "把盒子藏起来。"},
        {"word": "seek", "phonetic": "/siːk/", "meaning": "v. 寻找", "example_en": "Hide and seek.", "example_cn": "捉迷藏。"},
        {"word": "search", "phonetic": "/sɜːrtʃ/", "meaning": "v. 搜索", "example_en": "Search the room.", "example_cn": "搜查这个房间。"},
        {"word": "save", "phonetic": "/seɪv/", "meaning": "v. 拯救，保存", "example_en": "Save my life.", "example_cn": "救我的命。"},
        {"word": "succeed", "phonetic": "/səkˈsiːd/", "meaning": "v. 成功", "example_en": "You will succeed.", "example_cn": "你会成功的。"}
    ]
} # 闭合 GLOBAL_VOCAB_DB 大字典

# 将剩余的关卡（9-20）暂时先用 Level 8 填充，防止数组越界报错
for lvl in range(9, 21):
    GLOBAL_VOCAB_DB[lvl] = list(GLOBAL_VOCAB_DB[8])
